/* ═══════════════════════════════════════════
   CONSTANTS
   ═══════════════════════════════════════════ */

export const DEFAULT_CATS=[
  {id:"food",label:"Food",glyph:"◇"},
  {id:"transport",label:"Transport",glyph:"→"},
  {id:"social",label:"Social",glyph:"◎"},
  {id:"shopping",label:"Shopping",glyph:"□"},
  {id:"other",label:"Other",glyph:"·"},
];

/* Symbol choices for the new-category glyph field. Text glyphs only (no colour emoji). */
export const CAT_GLYPH_PRESETS=[
  "◇","◆","●","○","◎","◐","□","■","▢","▲",
  "△","▼","▽","★","☆","✦","✧","✱","✓","✗",
  "✚","✎","⚑","⌂","∞","§","¶","∅","≠","≈",
  "±","÷","×","⇄","➜","♪","⌘",
];

export const CURRENCIES={
  AFN:{code:"AFN",symbol:"؋",label:"Afghan Afghani",country:"Afghanistan",locale:"fa-AF"},
  ALL:{code:"ALL",symbol:"L",label:"Albanian Lek",country:"Albania",locale:"sq-AL"},
  DZD:{code:"DZD",symbol:"دج",label:"Algerian Dinar",country:"Algeria",locale:"ar-DZ"},
  AOA:{code:"AOA",symbol:"Kz",label:"Angolan Kwanza",country:"Angola",locale:"pt-AO"},
  ARS:{code:"ARS",symbol:"$",label:"Argentine Peso",country:"Argentina",locale:"es-AR"},
  AMD:{code:"AMD",symbol:"֏",label:"Armenian Dram",country:"Armenia",locale:"hy-AM"},
  AWG:{code:"AWG",symbol:"ƒ",label:"Aruban Florin",country:"Aruba",locale:"nl-AW"},
  AUD:{code:"AUD",symbol:"A$",label:"Australian Dollar",country:"Australia",locale:"en-AU"},
  AZN:{code:"AZN",symbol:"₼",label:"Azerbaijani Manat",country:"Azerbaijan",locale:"az-AZ"},
  BSD:{code:"BSD",symbol:"B$",label:"Bahamian Dollar",country:"Bahamas",locale:"en-BS"},
  BHD:{code:"BHD",symbol:"د.ب",label:"Bahraini Dinar",country:"Bahrain",locale:"ar-BH"},
  BDT:{code:"BDT",symbol:"৳",label:"Bangladeshi Taka",country:"Bangladesh",locale:"bn-BD"},
  BBD:{code:"BBD",symbol:"Bds$",label:"Barbadian Dollar",country:"Barbados",locale:"en-BB"},
  BYN:{code:"BYN",symbol:"Br",label:"Belarusian Ruble",country:"Belarus",locale:"be-BY"},
  BZD:{code:"BZD",symbol:"BZ$",label:"Belize Dollar",country:"Belize",locale:"en-BZ"},
  BMD:{code:"BMD",symbol:"BD$",label:"Bermudian Dollar",country:"Bermuda",locale:"en-BM"},
  BTN:{code:"BTN",symbol:"Nu.",label:"Bhutanese Ngultrum",country:"Bhutan",locale:"dz-BT"},
  BOB:{code:"BOB",symbol:"Bs.",label:"Bolivian Boliviano",country:"Bolivia",locale:"es-BO"},
  BAM:{code:"BAM",symbol:"KM",label:"Bosnian Convertible Mark",country:"Bosnia and Herzegovina",locale:"bs-BA"},
  BWP:{code:"BWP",symbol:"P",label:"Botswana Pula",country:"Botswana",locale:"en-BW"},
  BRL:{code:"BRL",symbol:"R$",label:"Brazilian Real",country:"Brazil",locale:"pt-BR"},
  BND:{code:"BND",symbol:"B$",label:"Brunei Dollar",country:"Brunei",locale:"ms-BN"},
  BIF:{code:"BIF",symbol:"FBu",label:"Burundian Franc",country:"Burundi",locale:"fr-BI"},
  KHR:{code:"KHR",symbol:"៛",label:"Cambodian Riel",country:"Cambodia",locale:"km-KH"},
  CAD:{code:"CAD",symbol:"C$",label:"Canadian Dollar",country:"Canada",locale:"en-CA"},
  CVE:{code:"CVE",symbol:"Esc",label:"Cape Verdean Escudo",country:"Cape Verde",locale:"pt-CV"},
  KYD:{code:"KYD",symbol:"CI$",label:"Cayman Islands Dollar",country:"Cayman Islands",locale:"en-KY"},
  XAF:{code:"XAF",symbol:"FCFA",label:"Central African CFA Franc",country:"Central African CFA",locale:"fr-CM"},
  CLP:{code:"CLP",symbol:"$",label:"Chilean Peso",country:"Chile",locale:"es-CL"},
  CNY:{code:"CNY",symbol:"¥",label:"Chinese Yuan",country:"China",locale:"zh-CN"},
  COP:{code:"COP",symbol:"$",label:"Colombian Peso",country:"Colombia",locale:"es-CO"},
  KMF:{code:"KMF",symbol:"CF",label:"Comorian Franc",country:"Comoros",locale:"fr-KM"},
  CRC:{code:"CRC",symbol:"₡",label:"Costa Rican Colón",country:"Costa Rica",locale:"es-CR"},
  CUP:{code:"CUP",symbol:"$",label:"Cuban Peso",country:"Cuba",locale:"es-CU"},
  XCG:{code:"XCG",symbol:"Cg",label:"Caribbean Guilder",country:"Curaçao",locale:"nl-CW"},
  CZK:{code:"CZK",symbol:"Kč",label:"Czech Koruna",country:"Czechia",locale:"cs-CZ"},
  DKK:{code:"DKK",symbol:"kr",label:"Danish Krone",country:"Denmark",locale:"da-DK"},
  DJF:{code:"DJF",symbol:"Fdj",label:"Djiboutian Franc",country:"Djibouti",locale:"fr-DJ"},
  DOP:{code:"DOP",symbol:"RD$",label:"Dominican Peso",country:"Dominican Republic",locale:"es-DO"},
  CDF:{code:"CDF",symbol:"FC",label:"Congolese Franc",country:"DR Congo",locale:"fr-CD"},
  XCD:{code:"XCD",symbol:"EC$",label:"East Caribbean Dollar",country:"Eastern Caribbean",locale:"en-AG"},
  EGP:{code:"EGP",symbol:"E£",label:"Egyptian Pound",country:"Egypt",locale:"ar-EG"},
  SVC:{code:"SVC",symbol:"₡",label:"Salvadoran Colón",country:"El Salvador",locale:"es-SV"},
  ERN:{code:"ERN",symbol:"Nfk",label:"Eritrean Nakfa",country:"Eritrea",locale:"ti-ER"},
  SZL:{code:"SZL",symbol:"L",label:"Swazi Lilangeni",country:"Eswatini",locale:"en-SZ"},
  ETB:{code:"ETB",symbol:"Br",label:"Ethiopian Birr",country:"Ethiopia",locale:"am-ET"},
  EUR:{code:"EUR",symbol:"€",label:"Euro",country:"Eurozone",locale:"de-DE"},
  FKP:{code:"FKP",symbol:"£",label:"Falkland Islands Pound",country:"Falkland Islands",locale:"en-FK"},
  FJD:{code:"FJD",symbol:"FJ$",label:"Fijian Dollar",country:"Fiji",locale:"en-FJ"},
  XPF:{code:"XPF",symbol:"₣",label:"CFP Franc",country:"French Pacific",locale:"fr-PF"},
  GMD:{code:"GMD",symbol:"D",label:"Gambian Dalasi",country:"Gambia",locale:"en-GM"},
  GEL:{code:"GEL",symbol:"₾",label:"Georgian Lari",country:"Georgia",locale:"ka-GE"},
  GHS:{code:"GHS",symbol:"₵",label:"Ghanaian Cedi",country:"Ghana",locale:"en-GH"},
  GIP:{code:"GIP",symbol:"£",label:"Gibraltar Pound",country:"Gibraltar",locale:"en-GI"},
  GTQ:{code:"GTQ",symbol:"Q",label:"Guatemalan Quetzal",country:"Guatemala",locale:"es-GT"},
  GNF:{code:"GNF",symbol:"FG",label:"Guinean Franc",country:"Guinea",locale:"fr-GN"},
  GYD:{code:"GYD",symbol:"G$",label:"Guyanese Dollar",country:"Guyana",locale:"en-GY"},
  HTG:{code:"HTG",symbol:"G",label:"Haitian Gourde",country:"Haiti",locale:"fr-HT"},
  HNL:{code:"HNL",symbol:"L",label:"Honduran Lempira",country:"Honduras",locale:"es-HN"},
  HKD:{code:"HKD",symbol:"HK$",label:"Hong Kong Dollar",country:"Hong Kong",locale:"zh-HK"},
  HUF:{code:"HUF",symbol:"Ft",label:"Hungarian Forint",country:"Hungary",locale:"hu-HU"},
  ISK:{code:"ISK",symbol:"kr",label:"Icelandic Króna",country:"Iceland",locale:"is-IS"},
  INR:{code:"INR",symbol:"₹",label:"Indian Rupee",country:"India",locale:"en-IN"},
  IDR:{code:"IDR",symbol:"Rp",label:"Indonesian Rupiah",country:"Indonesia",locale:"id-ID"},
  IRR:{code:"IRR",symbol:"﷼",label:"Iranian Rial",country:"Iran",locale:"fa-IR"},
  IQD:{code:"IQD",symbol:"ع.د",label:"Iraqi Dinar",country:"Iraq",locale:"ar-IQ"},
  ILS:{code:"ILS",symbol:"₪",label:"Israeli New Shekel",country:"Israel",locale:"he-IL"},
  JMD:{code:"JMD",symbol:"J$",label:"Jamaican Dollar",country:"Jamaica",locale:"en-JM"},
  JPY:{code:"JPY",symbol:"¥",label:"Japanese Yen",country:"Japan",locale:"ja-JP"},
  JOD:{code:"JOD",symbol:"د.ا",label:"Jordanian Dinar",country:"Jordan",locale:"ar-JO"},
  KZT:{code:"KZT",symbol:"₸",label:"Kazakhstani Tenge",country:"Kazakhstan",locale:"kk-KZ"},
  KES:{code:"KES",symbol:"KSh",label:"Kenyan Shilling",country:"Kenya",locale:"en-KE"},
  KWD:{code:"KWD",symbol:"د.ك",label:"Kuwaiti Dinar",country:"Kuwait",locale:"ar-KW"},
  KGS:{code:"KGS",symbol:"с",label:"Kyrgyzstani Som",country:"Kyrgyzstan",locale:"ky-KG"},
  LAK:{code:"LAK",symbol:"₭",label:"Lao Kip",country:"Laos",locale:"lo-LA"},
  LBP:{code:"LBP",symbol:"ل.ل",label:"Lebanese Pound",country:"Lebanon",locale:"ar-LB"},
  LSL:{code:"LSL",symbol:"L",label:"Lesotho Loti",country:"Lesotho",locale:"en-LS"},
  LRD:{code:"LRD",symbol:"L$",label:"Liberian Dollar",country:"Liberia",locale:"en-LR"},
  LYD:{code:"LYD",symbol:"ل.د",label:"Libyan Dinar",country:"Libya",locale:"ar-LY"},
  MOP:{code:"MOP",symbol:"MOP$",label:"Macanese Pataca",country:"Macau",locale:"zh-MO"},
  MGA:{code:"MGA",symbol:"Ar",label:"Malagasy Ariary",country:"Madagascar",locale:"mg-MG"},
  MWK:{code:"MWK",symbol:"MK",label:"Malawian Kwacha",country:"Malawi",locale:"en-MW"},
  MYR:{code:"MYR",symbol:"RM",label:"Malaysian Ringgit",country:"Malaysia",locale:"en-MY"},
  MVR:{code:"MVR",symbol:"Rf",label:"Maldivian Rufiyaa",country:"Maldives",locale:"dv-MV"},
  MRU:{code:"MRU",symbol:"UM",label:"Mauritanian Ouguiya",country:"Mauritania",locale:"ar-MR"},
  MUR:{code:"MUR",symbol:"₨",label:"Mauritian Rupee",country:"Mauritius",locale:"en-MU"},
  MXN:{code:"MXN",symbol:"Mex$",label:"Mexican Peso",country:"Mexico",locale:"es-MX"},
  MDL:{code:"MDL",symbol:"L",label:"Moldovan Leu",country:"Moldova",locale:"ro-MD"},
  MNT:{code:"MNT",symbol:"₮",label:"Mongolian Tögrög",country:"Mongolia",locale:"mn-MN"},
  MAD:{code:"MAD",symbol:"د.م.",label:"Moroccan Dirham",country:"Morocco",locale:"ar-MA"},
  MZN:{code:"MZN",symbol:"MT",label:"Mozambican Metical",country:"Mozambique",locale:"pt-MZ"},
  MMK:{code:"MMK",symbol:"K",label:"Myanmar Kyat",country:"Myanmar",locale:"my-MM"},
  NAD:{code:"NAD",symbol:"N$",label:"Namibian Dollar",country:"Namibia",locale:"en-NA"},
  NPR:{code:"NPR",symbol:"₨",label:"Nepalese Rupee",country:"Nepal",locale:"ne-NP"},
  NZD:{code:"NZD",symbol:"NZ$",label:"New Zealand Dollar",country:"New Zealand",locale:"en-NZ"},
  NIO:{code:"NIO",symbol:"C$",label:"Nicaraguan Córdoba",country:"Nicaragua",locale:"es-NI"},
  NGN:{code:"NGN",symbol:"₦",label:"Nigerian Naira",country:"Nigeria",locale:"en-NG"},
  KPW:{code:"KPW",symbol:"₩",label:"North Korean Won",country:"North Korea",locale:"ko-KP"},
  MKD:{code:"MKD",symbol:"ден",label:"Macedonian Denar",country:"North Macedonia",locale:"mk-MK"},
  NOK:{code:"NOK",symbol:"kr",label:"Norwegian Krone",country:"Norway",locale:"nb-NO"},
  OMR:{code:"OMR",symbol:"ر.ع.",label:"Omani Rial",country:"Oman",locale:"ar-OM"},
  PKR:{code:"PKR",symbol:"₨",label:"Pakistani Rupee",country:"Pakistan",locale:"en-PK"},
  PAB:{code:"PAB",symbol:"B/.",label:"Panamanian Balboa",country:"Panama",locale:"es-PA"},
  PGK:{code:"PGK",symbol:"K",label:"Papua New Guinean Kina",country:"Papua New Guinea",locale:"en-PG"},
  PYG:{code:"PYG",symbol:"₲",label:"Paraguayan Guaraní",country:"Paraguay",locale:"es-PY"},
  PEN:{code:"PEN",symbol:"S/",label:"Peruvian Sol",country:"Peru",locale:"es-PE"},
  PHP:{code:"PHP",symbol:"₱",label:"Philippine Peso",country:"Philippines",locale:"en-PH"},
  PLN:{code:"PLN",symbol:"zł",label:"Polish Złoty",country:"Poland",locale:"pl-PL"},
  QAR:{code:"QAR",symbol:"ر.ق",label:"Qatari Riyal",country:"Qatar",locale:"ar-QA"},
  RON:{code:"RON",symbol:"lei",label:"Romanian Leu",country:"Romania",locale:"ro-RO"},
  RUB:{code:"RUB",symbol:"₽",label:"Russian Ruble",country:"Russia",locale:"ru-RU"},
  RWF:{code:"RWF",symbol:"FRw",label:"Rwandan Franc",country:"Rwanda",locale:"rw-RW"},
  SHP:{code:"SHP",symbol:"£",label:"Saint Helena Pound",country:"Saint Helena",locale:"en-SH"},
  WST:{code:"WST",symbol:"T",label:"Samoan Tālā",country:"Samoa",locale:"sm-WS"},
  STN:{code:"STN",symbol:"Db",label:"São Tomé and Príncipe Dobra",country:"São Tomé and Príncipe",locale:"pt-ST"},
  SAR:{code:"SAR",symbol:"ر.س",label:"Saudi Riyal",country:"Saudi Arabia",locale:"ar-SA"},
  RSD:{code:"RSD",symbol:"дин",label:"Serbian Dinar",country:"Serbia",locale:"sr-RS"},
  SCR:{code:"SCR",symbol:"₨",label:"Seychellois Rupee",country:"Seychelles",locale:"en-SC"},
  SLE:{code:"SLE",symbol:"Le",label:"Sierra Leonean Leone",country:"Sierra Leone",locale:"en-SL"},
  SGD:{code:"SGD",symbol:"S$",label:"Singapore Dollar",country:"Singapore",locale:"en-SG"},
  SBD:{code:"SBD",symbol:"SI$",label:"Solomon Islands Dollar",country:"Solomon Islands",locale:"en-SB"},
  SOS:{code:"SOS",symbol:"Sh",label:"Somali Shilling",country:"Somalia",locale:"so-SO"},
  ZAR:{code:"ZAR",symbol:"R",label:"South African Rand",country:"South Africa",locale:"en-ZA"},
  KRW:{code:"KRW",symbol:"₩",label:"South Korean Won",country:"South Korea",locale:"ko-KR"},
  SSP:{code:"SSP",symbol:"£",label:"South Sudanese Pound",country:"South Sudan",locale:"en-SS"},
  LKR:{code:"LKR",symbol:"Rs",label:"Sri Lankan Rupee",country:"Sri Lanka",locale:"si-LK"},
  SDG:{code:"SDG",symbol:"ج.س",label:"Sudanese Pound",country:"Sudan",locale:"ar-SD"},
  SRD:{code:"SRD",symbol:"$",label:"Surinamese Dollar",country:"Suriname",locale:"nl-SR"},
  SEK:{code:"SEK",symbol:"kr",label:"Swedish Krona",country:"Sweden",locale:"sv-SE"},
  CHF:{code:"CHF",symbol:"Fr",label:"Swiss Franc",country:"Switzerland",locale:"de-CH"},
  SYP:{code:"SYP",symbol:"£",label:"Syrian Pound",country:"Syria",locale:"ar-SY"},
  TWD:{code:"TWD",symbol:"NT$",label:"New Taiwan Dollar",country:"Taiwan",locale:"zh-TW"},
  TJS:{code:"TJS",symbol:"ЅМ",label:"Tajikistani Somoni",country:"Tajikistan",locale:"tg-TJ"},
  TZS:{code:"TZS",symbol:"TSh",label:"Tanzanian Shilling",country:"Tanzania",locale:"sw-TZ"},
  THB:{code:"THB",symbol:"฿",label:"Thai Baht",country:"Thailand",locale:"th-TH"},
  TOP:{code:"TOP",symbol:"T$",label:"Tongan Paʻanga",country:"Tonga",locale:"to-TO"},
  TTD:{code:"TTD",symbol:"TT$",label:"Trinidad and Tobago Dollar",country:"Trinidad and Tobago",locale:"en-TT"},
  TND:{code:"TND",symbol:"د.ت",label:"Tunisian Dinar",country:"Tunisia",locale:"ar-TN"},
  TRY:{code:"TRY",symbol:"₺",label:"Turkish Lira",country:"Turkey",locale:"tr-TR"},
  TMT:{code:"TMT",symbol:"m",label:"Turkmenistani Manat",country:"Turkmenistan",locale:"tk-TM"},
  UGX:{code:"UGX",symbol:"USh",label:"Ugandan Shilling",country:"Uganda",locale:"en-UG"},
  UAH:{code:"UAH",symbol:"₴",label:"Ukrainian Hryvnia",country:"Ukraine",locale:"uk-UA"},
  AED:{code:"AED",symbol:"د.إ",label:"UAE Dirham",country:"United Arab Emirates",locale:"ar-AE"},
  GBP:{code:"GBP",symbol:"£",label:"British Pound",country:"United Kingdom",locale:"en-GB"},
  USD:{code:"USD",symbol:"$",label:"US Dollar",country:"United States",locale:"en-US"},
  UYU:{code:"UYU",symbol:"$U",label:"Uruguayan Peso",country:"Uruguay",locale:"es-UY"},
  UZS:{code:"UZS",symbol:"so'm",label:"Uzbekistani Som",country:"Uzbekistan",locale:"uz-UZ"},
  VUV:{code:"VUV",symbol:"VT",label:"Vanuatu Vatu",country:"Vanuatu",locale:"bi-VU"},
  VES:{code:"VES",symbol:"Bs",label:"Venezuelan Bolívar",country:"Venezuela",locale:"es-VE"},
  VND:{code:"VND",symbol:"₫",label:"Vietnamese Đồng",country:"Vietnam",locale:"vi-VN"},
  XOF:{code:"XOF",symbol:"CFA",label:"West African CFA Franc",country:"West African CFA",locale:"fr-SN"},
  YER:{code:"YER",symbol:"﷼",label:"Yemeni Rial",country:"Yemen",locale:"ar-YE"},
  ZMW:{code:"ZMW",symbol:"ZK",label:"Zambian Kwacha",country:"Zambia",locale:"en-ZM"},
  ZWG:{code:"ZWG",symbol:"ZiG",label:"Zimbabwe Gold",country:"Zimbabwe",locale:"en-ZW"},
};

export const PRESETS={
  mono:{name:'Mono',bg:'#000000',surface:'#000000',surface2:'#0a0a0a',text:'#ffffff',textDim:'#9a9a9a',textMuted:'#5c5c5c',border:'rgba(255,255,255,0.10)',borderStrong:'rgba(255,255,255,0.22)',accent:'#ffffff',accentFg:'#000000',negative:'#ff5c5c',warning:'#e8c15a',positive:'#5bd488',catColors:{food:'#5b9fd4',transport:'#e8c15a',social:'#ff6b8b',shopping:'#a68bfa',other:'#5bd488'}},
  graphite:{name:'Graphite',bg:'#111318',surface:'#1a1d24',surface2:'#23272f',text:'#e4e6ea',textDim:'#8b919e',textMuted:'#555b66',border:'rgba(255,255,255,0.07)',borderStrong:'rgba(255,255,255,0.14)',accent:'#8b9eff',accentFg:'#0d0f16',negative:'#f06b6b',warning:'#e3b341',positive:'#7ee787',catColors:{food:'#8b9eff',transport:'#e3b341',social:'#f06b6b',shopping:'#a371f7',other:'#768390'}},
  forest:{name:'Forest',bg:'#0a100d',surface:'#131f19',surface2:'#1b2b23',text:'#dfeae4',textDim:'#86a092',textMuted:'#4e6458',border:'rgba(255,255,255,0.06)',borderStrong:'rgba(255,255,255,0.14)',accent:'#6caf82',accentFg:'#0a100d',negative:'#d47070',warning:'#d4a55a',positive:'#6caf82',catColors:{food:'#6caf82',transport:'#d4a55a',social:'#d47070',shopping:'#7da29e',other:'#8a8f7d'}},
  paper:{name:'Paper',bg:'#fafaf7',surface:'#ffffff',surface2:'#f0f0eb',text:'#1a1a17',textDim:'#5a5a55',textMuted:'#9a9a95',border:'rgba(0,0,0,0.07)',borderStrong:'rgba(0,0,0,0.14)',accent:'#1a1a17',accentFg:'#fafaf7',negative:'#c04a30',warning:'#c07a20',positive:'#3a7a3a',catColors:{food:'#3a7a3a',transport:'#c07a20',social:'#c04a30',shopping:'#5c4a7a',other:'#6a6a65'}},
  daylight:{name:'Daylight',bg:'#f4f6f9',surface:'#ffffff',surface2:'#eef1f6',text:'#111318',textDim:'#4a5568',textMuted:'#9099a8',border:'rgba(0,0,0,0.07)',borderStrong:'rgba(0,0,0,0.14)',accent:'#2563eb',accentFg:'#ffffff',negative:'#dc2626',warning:'#d97706',positive:'#16a34a',catColors:{food:'#2563eb',transport:'#d97706',social:'#dc2626',shopping:'#7c3aed',other:'#64748b'}},
  sakura:{name:'Sakura',bg:'#fdf4f7',surface:'#ffffff',surface2:'#fbe8ef',text:'#3a2029',textDim:'#8a6570',textMuted:'#b49aa2',border:'rgba(58,32,41,0.08)',borderStrong:'rgba(58,32,41,0.16)',accent:'#d1476f',accentFg:'#ffffff',negative:'#c0392b',warning:'#a8761a',positive:'#3f8a5a',catColors:{food:'#d1476f',transport:'#a8761a',social:'#c0392b',shopping:'#9b5fb0',other:'#8a7170'}},
  linen:{name:'Linen',bg:'#efeae0',surface:'#f8f4ea',surface2:'#e3ddd0',text:'#1f1a12',textDim:'#5a5040',textMuted:'#9a9080',border:'rgba(31,26,18,0.08)',borderStrong:'rgba(31,26,18,0.16)',accent:'#8a5a3a',accentFg:'#f8f4ea',negative:'#a03828',warning:'#a06818',positive:'#4a7248',catColors:{food:'#8a5a3a',transport:'#a06818',social:'#a03828',shopping:'#6a5088',other:'#6a6055'}},
};
export const DEFAULT_THEME=PRESETS.paper;

export const FONT_OPTIONS=[
  {id:'inter',name:'Inter',stack:"'Inter',system-ui,-apple-system,BlinkMacSystemFont,sans-serif"},
  {id:'system',name:'System UI',stack:"system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"},
  {id:'poppins',name:'Poppins',stack:"'Poppins',system-ui,sans-serif"},
  {id:'grotesk',name:'Space Grotesk',stack:"'Space Grotesk',system-ui,sans-serif"},
  {id:'serif',name:'Source Serif',stack:"'Source Serif 4',Georgia,'Times New Roman',serif"},
  {id:'mono',name:'JetBrains Mono',stack:"'JetBrains Mono',ui-monospace,'Cascadia Code',monospace"},
  {id:'fredoka',name:'Fredoka',stack:"'Fredoka',system-ui,sans-serif"},
];

export const CAT_COLOR_PRESETS=[null,'#ff8a3d','#ff5c93','#ffd93d','#5bd488','#5b9fd4','#a68bfa','#f5f5f5','#2a2a2a'];

/* GitHub-style spending heatmap — base (empty days) + 4 intensity levels */
export const HEAT_DEFAULT_COLORS={l0:'transparent',l1:'#9be9a8',l2:'#40c463',l3:'#30a14e',l4:'#216e39'};
export const HEAT_PRESETS={
  github:{name:'GitHub',colors:{l0:'transparent',l1:'#9be9a8',l2:'#40c463',l3:'#30a14e',l4:'#216e39'}},
  githubDark:{name:'GitHub dark',colors:{l0:'#161b22',l1:'#0e4429',l2:'#006d32',l3:'#26a641',l4:'#39d353'}},
  ocean:{name:'Ocean',colors:{l0:'transparent',l1:'#a8c8f0',l2:'#5b9fd4',l3:'#2f6fb8',l4:'#1e3f8f'}},
  purple:{name:'Purple',colors:{l0:'transparent',l1:'#d8c8f5',l2:'#b08cff',l3:'#8a5cf5',l4:'#5a2db0'}},
  warm:{name:'Warm',colors:{l0:'transparent',l1:'#ffdfb0',l2:'#ffb066',l3:'#f57c3d',l4:'#c2402a'}},
};

/* ─── Piggy bank ─── */
export const PIGGY_GIF="https://terraria.wiki.gg/images/Flying_Piggy_Bank_%28animated%29.gif?63ff5d";
export const FREQ_OPTIONS={daily:"Daily",weekly:"Weekly",monthly:"Monthly"};

export const PREF_DEFAULTS={
  currency:"MYR",compact:false,pieThickness:3.6,pieGap:0,groupHistory:true,
  tilt:true,
  trendStyle:'line', // 'line' | 'heatmap'
  heatColors:{l0:'transparent',l1:'#9be9a8',l2:'#40c463',l3:'#30a14e',l4:'#216e39'},
  wallpaper:null,wallpaperDim:60,
  uiBlur:16,uiOpacity:96,wallBlur:0,
  font:"inter",weather:"none",weatherSpeed:1,
  catEnabled:true,catColor:null,
  customFonts:[],
  cardOrder:['log','breakdown','trend','history','backup'],
  cardPanel:null,cardPanelOpacity:100,
  balancesEnabled:true, // 'true' = banking-style balance, 'false' = plain budgeting (old behavior)
  overspendFromBalance:true, // true = overspends drain the bank balance, false = covered by monthly budget
  heroMode:'daily',     // 'daily' = hero shows today's allowance, 'balance' = hero shows bank balance
  piggyTexture:null,piggySound:true,piggySoundId:'coin',piggySoundCustom:null,
  budgetAlerts:true, // in-app alerts at 80% / 100% of category and monthly budgets
  appLock:false,     // require a PIN to open the app
  streakGrace:0,     // missed days forgiven inside a spend streak (0 = off)
  edgeBlur:true,     // progressive blur+fade at the top and bottom of the app (Android)
  lang:'en',         // UI language: en | es | zh | ru | th | ja | ko
  travel:{active:false,name:'',currency:'USD',rate:1,start:'',rateAuto:true,rateUpdatedAt:''}, // travel mode — log in a foreign currency
};

export const DEFAULT_CARD_ORDER=['log','breakdown','trend','history','insights','streak','auto','piggy','backup'];
