package com.ledger.app.util

import java.text.NumberFormat
import java.util.Locale
import kotlin.math.abs

data class CurrencyInfo(
    val code: String,
    val symbol: String,
    val label: String,
    val country: String,
    val locale: Locale,
)

val CURRENCIES: Map<String, CurrencyInfo> = mapOf(
    "AFN" to CurrencyInfo("AFN", "؋", "Afghan Afghani", "Afghanistan", Locale("fa", "AF")),
    "ALL" to CurrencyInfo("ALL", "L", "Albanian Lek", "Albania", Locale("sq", "AL")),
    "DZD" to CurrencyInfo("DZD", "دج", "Algerian Dinar", "Algeria", Locale("ar", "DZ")),
    "AOA" to CurrencyInfo("AOA", "Kz", "Angolan Kwanza", "Angola", Locale("pt", "AO")),
    "ARS" to CurrencyInfo("ARS", "$", "Argentine Peso", "Argentina", Locale("es", "AR")),
    "AMD" to CurrencyInfo("AMD", "֏", "Armenian Dram", "Armenia", Locale("hy", "AM")),
    "AWG" to CurrencyInfo("AWG", "ƒ", "Aruban Florin", "Aruba", Locale("nl", "AW")),
    "AUD" to CurrencyInfo("AUD", "A$", "Australian Dollar", "Australia", Locale("en", "AU")),
    "AZN" to CurrencyInfo("AZN", "₼", "Azerbaijani Manat", "Azerbaijan", Locale("az", "AZ")),
    "BSD" to CurrencyInfo("BSD", "B$", "Bahamian Dollar", "Bahamas", Locale("en", "BS")),
    "BHD" to CurrencyInfo("BHD", "د.ب", "Bahraini Dinar", "Bahrain", Locale("ar", "BH")),
    "BDT" to CurrencyInfo("BDT", "৳", "Bangladeshi Taka", "Bangladesh", Locale("bn", "BD")),
    "BBD" to CurrencyInfo("BBD", "Bds$", "Barbadian Dollar", "Barbados", Locale("en", "BB")),
    "BYN" to CurrencyInfo("BYN", "Br", "Belarusian Ruble", "Belarus", Locale("be", "BY")),
    "BZD" to CurrencyInfo("BZD", "BZ$", "Belize Dollar", "Belize", Locale("en", "BZ")),
    "BMD" to CurrencyInfo("BMD", "BD$", "Bermudian Dollar", "Bermuda", Locale("en", "BM")),
    "BTN" to CurrencyInfo("BTN", "Nu.", "Bhutanese Ngultrum", "Bhutan", Locale("dz", "BT")),
    "BOB" to CurrencyInfo("BOB", "Bs.", "Bolivian Boliviano", "Bolivia", Locale("es", "BO")),
    "BAM" to CurrencyInfo("BAM", "KM", "Bosnian Convertible Mark", "Bosnia and Herzegovina", Locale("bs", "BA")),
    "BWP" to CurrencyInfo("BWP", "P", "Botswana Pula", "Botswana", Locale("en", "BW")),
    "BRL" to CurrencyInfo("BRL", "R$", "Brazilian Real", "Brazil", Locale("pt", "BR")),
    "BND" to CurrencyInfo("BND", "B$", "Brunei Dollar", "Brunei", Locale("ms", "BN")),
    "BIF" to CurrencyInfo("BIF", "FBu", "Burundian Franc", "Burundi", Locale("fr", "BI")),
    "KHR" to CurrencyInfo("KHR", "៛", "Cambodian Riel", "Cambodia", Locale("km", "KH")),
    "CAD" to CurrencyInfo("CAD", "C$", "Canadian Dollar", "Canada", Locale("en", "CA")),
    "CVE" to CurrencyInfo("CVE", "Esc", "Cape Verdean Escudo", "Cape Verde", Locale("pt", "CV")),
    "KYD" to CurrencyInfo("KYD", "CI$", "Cayman Islands Dollar", "Cayman Islands", Locale("en", "KY")),
    "XAF" to CurrencyInfo("XAF", "FCFA", "Central African CFA Franc", "Central African CFA", Locale("fr", "CM")),
    "CLP" to CurrencyInfo("CLP", "$", "Chilean Peso", "Chile", Locale("es", "CL")),
    "CNY" to CurrencyInfo("CNY", "¥", "Chinese Yuan", "China", Locale("zh", "CN")),
    "COP" to CurrencyInfo("COP", "$", "Colombian Peso", "Colombia", Locale("es", "CO")),
    "KMF" to CurrencyInfo("KMF", "CF", "Comorian Franc", "Comoros", Locale("fr", "KM")),
    "CRC" to CurrencyInfo("CRC", "₡", "Costa Rican Colón", "Costa Rica", Locale("es", "CR")),
    "CUP" to CurrencyInfo("CUP", "$", "Cuban Peso", "Cuba", Locale("es", "CU")),
    "XCG" to CurrencyInfo("XCG", "Cg", "Caribbean Guilder", "Curaçao", Locale("nl", "CW")),
    "CZK" to CurrencyInfo("CZK", "Kč", "Czech Koruna", "Czechia", Locale("cs", "CZ")),
    "DKK" to CurrencyInfo("DKK", "kr", "Danish Krone", "Denmark", Locale("da", "DK")),
    "DJF" to CurrencyInfo("DJF", "Fdj", "Djiboutian Franc", "Djibouti", Locale("fr", "DJ")),
    "DOP" to CurrencyInfo("DOP", "RD$", "Dominican Peso", "Dominican Republic", Locale("es", "DO")),
    "CDF" to CurrencyInfo("CDF", "FC", "Congolese Franc", "DR Congo", Locale("fr", "CD")),
    "XCD" to CurrencyInfo("XCD", "EC$", "East Caribbean Dollar", "Eastern Caribbean", Locale("en", "AG")),
    "EGP" to CurrencyInfo("EGP", "E£", "Egyptian Pound", "Egypt", Locale("ar", "EG")),
    "SVC" to CurrencyInfo("SVC", "₡", "Salvadoran Colón", "El Salvador", Locale("es", "SV")),
    "ERN" to CurrencyInfo("ERN", "Nfk", "Eritrean Nakfa", "Eritrea", Locale("ti", "ER")),
    "SZL" to CurrencyInfo("SZL", "L", "Swazi Lilangeni", "Eswatini", Locale("en", "SZ")),
    "ETB" to CurrencyInfo("ETB", "Br", "Ethiopian Birr", "Ethiopia", Locale("am", "ET")),
    "EUR" to CurrencyInfo("EUR", "€", "Euro", "Eurozone", Locale("de", "DE")),
    "FKP" to CurrencyInfo("FKP", "£", "Falkland Islands Pound", "Falkland Islands", Locale("en", "FK")),
    "FJD" to CurrencyInfo("FJD", "FJ$", "Fijian Dollar", "Fiji", Locale("en", "FJ")),
    "XPF" to CurrencyInfo("XPF", "₣", "CFP Franc", "French Pacific", Locale("fr", "PF")),
    "GMD" to CurrencyInfo("GMD", "D", "Gambian Dalasi", "Gambia", Locale("en", "GM")),
    "GEL" to CurrencyInfo("GEL", "₾", "Georgian Lari", "Georgia", Locale("ka", "GE")),
    "GHS" to CurrencyInfo("GHS", "₵", "Ghanaian Cedi", "Ghana", Locale("en", "GH")),
    "GIP" to CurrencyInfo("GIP", "£", "Gibraltar Pound", "Gibraltar", Locale("en", "GI")),
    "GTQ" to CurrencyInfo("GTQ", "Q", "Guatemalan Quetzal", "Guatemala", Locale("es", "GT")),
    "GNF" to CurrencyInfo("GNF", "FG", "Guinean Franc", "Guinea", Locale("fr", "GN")),
    "GYD" to CurrencyInfo("GYD", "G$", "Guyanese Dollar", "Guyana", Locale("en", "GY")),
    "HTG" to CurrencyInfo("HTG", "G", "Haitian Gourde", "Haiti", Locale("fr", "HT")),
    "HNL" to CurrencyInfo("HNL", "L", "Honduran Lempira", "Honduras", Locale("es", "HN")),
    "HKD" to CurrencyInfo("HKD", "HK$", "Hong Kong Dollar", "Hong Kong", Locale("zh", "HK")),
    "HUF" to CurrencyInfo("HUF", "Ft", "Hungarian Forint", "Hungary", Locale("hu", "HU")),
    "ISK" to CurrencyInfo("ISK", "kr", "Icelandic Króna", "Iceland", Locale("is", "IS")),
    "INR" to CurrencyInfo("INR", "₹", "Indian Rupee", "India", Locale("en", "IN")),
    "IDR" to CurrencyInfo("IDR", "Rp", "Indonesian Rupiah", "Indonesia", Locale("id", "ID")),
    "IRR" to CurrencyInfo("IRR", "﷼", "Iranian Rial", "Iran", Locale("fa", "IR")),
    "IQD" to CurrencyInfo("IQD", "ع.د", "Iraqi Dinar", "Iraq", Locale("ar", "IQ")),
    "ILS" to CurrencyInfo("ILS", "₪", "Israeli New Shekel", "Israel", Locale("he", "IL")),
    "JMD" to CurrencyInfo("JMD", "J$", "Jamaican Dollar", "Jamaica", Locale("en", "JM")),
    "JPY" to CurrencyInfo("JPY", "¥", "Japanese Yen", "Japan", Locale("ja", "JP")),
    "JOD" to CurrencyInfo("JOD", "د.ا", "Jordanian Dinar", "Jordan", Locale("ar", "JO")),
    "KZT" to CurrencyInfo("KZT", "₸", "Kazakhstani Tenge", "Kazakhstan", Locale("kk", "KZ")),
    "KES" to CurrencyInfo("KES", "KSh", "Kenyan Shilling", "Kenya", Locale("en", "KE")),
    "KWD" to CurrencyInfo("KWD", "د.ك", "Kuwaiti Dinar", "Kuwait", Locale("ar", "KW")),
    "KGS" to CurrencyInfo("KGS", "с", "Kyrgyzstani Som", "Kyrgyzstan", Locale("ky", "KG")),
    "LAK" to CurrencyInfo("LAK", "₭", "Lao Kip", "Laos", Locale("lo", "LA")),
    "LBP" to CurrencyInfo("LBP", "ل.ل", "Lebanese Pound", "Lebanon", Locale("ar", "LB")),
    "LSL" to CurrencyInfo("LSL", "L", "Lesotho Loti", "Lesotho", Locale("en", "LS")),
    "LRD" to CurrencyInfo("LRD", "L$", "Liberian Dollar", "Liberia", Locale("en", "LR")),
    "LYD" to CurrencyInfo("LYD", "ل.د", "Libyan Dinar", "Libya", Locale("ar", "LY")),
    "MOP" to CurrencyInfo("MOP", "MOP$", "Macanese Pataca", "Macau", Locale("zh", "MO")),
    "MGA" to CurrencyInfo("MGA", "Ar", "Malagasy Ariary", "Madagascar", Locale("mg", "MG")),
    "MWK" to CurrencyInfo("MWK", "MK", "Malawian Kwacha", "Malawi", Locale("en", "MW")),
    "MYR" to CurrencyInfo("MYR", "RM", "Malaysian Ringgit", "Malaysia", Locale("en", "MY")),
    "MVR" to CurrencyInfo("MVR", "Rf", "Maldivian Rufiyaa", "Maldives", Locale("dv", "MV")),
    "MRU" to CurrencyInfo("MRU", "UM", "Mauritanian Ouguiya", "Mauritania", Locale("ar", "MR")),
    "MUR" to CurrencyInfo("MUR", "₨", "Mauritian Rupee", "Mauritius", Locale("en", "MU")),
    "MXN" to CurrencyInfo("MXN", "Mex$", "Mexican Peso", "Mexico", Locale("es", "MX")),
    "MDL" to CurrencyInfo("MDL", "L", "Moldovan Leu", "Moldova", Locale("ro", "MD")),
    "MNT" to CurrencyInfo("MNT", "₮", "Mongolian Tögrög", "Mongolia", Locale("mn", "MN")),
    "MAD" to CurrencyInfo("MAD", "د.م.", "Moroccan Dirham", "Morocco", Locale("ar", "MA")),
    "MZN" to CurrencyInfo("MZN", "MT", "Mozambican Metical", "Mozambique", Locale("pt", "MZ")),
    "MMK" to CurrencyInfo("MMK", "K", "Myanmar Kyat", "Myanmar", Locale("my", "MM")),
    "NAD" to CurrencyInfo("NAD", "N$", "Namibian Dollar", "Namibia", Locale("en", "NA")),
    "NPR" to CurrencyInfo("NPR", "₨", "Nepalese Rupee", "Nepal", Locale("ne", "NP")),
    "NZD" to CurrencyInfo("NZD", "NZ$", "New Zealand Dollar", "New Zealand", Locale("en", "NZ")),
    "NIO" to CurrencyInfo("NIO", "C$", "Nicaraguan Córdoba", "Nicaragua", Locale("es", "NI")),
    "NGN" to CurrencyInfo("NGN", "₦", "Nigerian Naira", "Nigeria", Locale("en", "NG")),
    "KPW" to CurrencyInfo("KPW", "₩", "North Korean Won", "North Korea", Locale("ko", "KP")),
    "MKD" to CurrencyInfo("MKD", "ден", "Macedonian Denar", "North Macedonia", Locale("mk", "MK")),
    "NOK" to CurrencyInfo("NOK", "kr", "Norwegian Krone", "Norway", Locale("nb", "NO")),
    "OMR" to CurrencyInfo("OMR", "ر.ع.", "Omani Rial", "Oman", Locale("ar", "OM")),
    "PKR" to CurrencyInfo("PKR", "₨", "Pakistani Rupee", "Pakistan", Locale("en", "PK")),
    "PAB" to CurrencyInfo("PAB", "B/.", "Panamanian Balboa", "Panama", Locale("es", "PA")),
    "PGK" to CurrencyInfo("PGK", "K", "Papua New Guinean Kina", "Papua New Guinea", Locale("en", "PG")),
    "PYG" to CurrencyInfo("PYG", "₲", "Paraguayan Guaraní", "Paraguay", Locale("es", "PY")),
    "PEN" to CurrencyInfo("PEN", "S/", "Peruvian Sol", "Peru", Locale("es", "PE")),
    "PHP" to CurrencyInfo("PHP", "₱", "Philippine Peso", "Philippines", Locale("en", "PH")),
    "PLN" to CurrencyInfo("PLN", "zł", "Polish Złoty", "Poland", Locale("pl", "PL")),
    "QAR" to CurrencyInfo("QAR", "ر.ق", "Qatari Riyal", "Qatar", Locale("ar", "QA")),
    "RON" to CurrencyInfo("RON", "lei", "Romanian Leu", "Romania", Locale("ro", "RO")),
    "RUB" to CurrencyInfo("RUB", "₽", "Russian Ruble", "Russia", Locale("ru", "RU")),
    "RWF" to CurrencyInfo("RWF", "FRw", "Rwandan Franc", "Rwanda", Locale("rw", "RW")),
    "SHP" to CurrencyInfo("SHP", "£", "Saint Helena Pound", "Saint Helena", Locale("en", "SH")),
    "WST" to CurrencyInfo("WST", "T", "Samoan Tālā", "Samoa", Locale("sm", "WS")),
    "STN" to CurrencyInfo("STN", "Db", "São Tomé and Príncipe Dobra", "São Tomé and Príncipe", Locale("pt", "ST")),
    "SAR" to CurrencyInfo("SAR", "ر.س", "Saudi Riyal", "Saudi Arabia", Locale("ar", "SA")),
    "RSD" to CurrencyInfo("RSD", "дин", "Serbian Dinar", "Serbia", Locale("sr", "RS")),
    "SCR" to CurrencyInfo("SCR", "₨", "Seychellois Rupee", "Seychelles", Locale("en", "SC")),
    "SLE" to CurrencyInfo("SLE", "Le", "Sierra Leonean Leone", "Sierra Leone", Locale("en", "SL")),
    "SGD" to CurrencyInfo("SGD", "S$", "Singapore Dollar", "Singapore", Locale("en", "SG")),
    "SBD" to CurrencyInfo("SBD", "SI$", "Solomon Islands Dollar", "Solomon Islands", Locale("en", "SB")),
    "SOS" to CurrencyInfo("SOS", "Sh", "Somali Shilling", "Somalia", Locale("so", "SO")),
    "ZAR" to CurrencyInfo("ZAR", "R", "South African Rand", "South Africa", Locale("en", "ZA")),
    "KRW" to CurrencyInfo("KRW", "₩", "South Korean Won", "South Korea", Locale("ko", "KR")),
    "SSP" to CurrencyInfo("SSP", "£", "South Sudanese Pound", "South Sudan", Locale("en", "SS")),
    "LKR" to CurrencyInfo("LKR", "Rs", "Sri Lankan Rupee", "Sri Lanka", Locale("si", "LK")),
    "SDG" to CurrencyInfo("SDG", "ج.س", "Sudanese Pound", "Sudan", Locale("ar", "SD")),
    "SRD" to CurrencyInfo("SRD", "$", "Surinamese Dollar", "Suriname", Locale("nl", "SR")),
    "SEK" to CurrencyInfo("SEK", "kr", "Swedish Krona", "Sweden", Locale("sv", "SE")),
    "CHF" to CurrencyInfo("CHF", "Fr", "Swiss Franc", "Switzerland", Locale("de", "CH")),
    "SYP" to CurrencyInfo("SYP", "£", "Syrian Pound", "Syria", Locale("ar", "SY")),
    "TWD" to CurrencyInfo("TWD", "NT$", "New Taiwan Dollar", "Taiwan", Locale("zh", "TW")),
    "TJS" to CurrencyInfo("TJS", "ЅМ", "Tajikistani Somoni", "Tajikistan", Locale("tg", "TJ")),
    "TZS" to CurrencyInfo("TZS", "TSh", "Tanzanian Shilling", "Tanzania", Locale("sw", "TZ")),
    "THB" to CurrencyInfo("THB", "฿", "Thai Baht", "Thailand", Locale("th", "TH")),
    "TOP" to CurrencyInfo("TOP", "T$", "Tongan Paʻanga", "Tonga", Locale("to", "TO")),
    "TTD" to CurrencyInfo("TTD", "TT$", "Trinidad and Tobago Dollar", "Trinidad and Tobago", Locale("en", "TT")),
    "TND" to CurrencyInfo("TND", "د.ت", "Tunisian Dinar", "Tunisia", Locale("ar", "TN")),
    "TRY" to CurrencyInfo("TRY", "₺", "Turkish Lira", "Turkey", Locale("tr", "TR")),
    "TMT" to CurrencyInfo("TMT", "m", "Turkmenistani Manat", "Turkmenistan", Locale("tk", "TM")),
    "UGX" to CurrencyInfo("UGX", "USh", "Ugandan Shilling", "Uganda", Locale("en", "UG")),
    "UAH" to CurrencyInfo("UAH", "₴", "Ukrainian Hryvnia", "Ukraine", Locale("uk", "UA")),
    "AED" to CurrencyInfo("AED", "د.إ", "UAE Dirham", "United Arab Emirates", Locale("ar", "AE")),
    "GBP" to CurrencyInfo("GBP", "£", "British Pound", "United Kingdom", Locale("en", "GB")),
    "USD" to CurrencyInfo("USD", "$", "US Dollar", "United States", Locale("en", "US")),
    "UYU" to CurrencyInfo("UYU", "\$U", "Uruguayan Peso", "Uruguay", Locale("es", "UY")),
    "UZS" to CurrencyInfo("UZS", "so'm", "Uzbekistani Som", "Uzbekistan", Locale("uz", "UZ")),
    "VUV" to CurrencyInfo("VUV", "VT", "Vanuatu Vatu", "Vanuatu", Locale("bi", "VU")),
    "VES" to CurrencyInfo("VES", "Bs", "Venezuelan Bolívar", "Venezuela", Locale("es", "VE")),
    "VND" to CurrencyInfo("VND", "₫", "Vietnamese Đồng", "Vietnam", Locale("vi", "VN")),
    "XOF" to CurrencyInfo("XOF", "CFA", "West African CFA Franc", "West African CFA", Locale("fr", "SN")),
    "YER" to CurrencyInfo("YER", "﷼", "Yemeni Rial", "Yemen", Locale("ar", "YE")),
    "ZMW" to CurrencyInfo("ZMW", "ZK", "Zambian Kwacha", "Zambia", Locale("en", "ZM")),
    "ZWG" to CurrencyInfo("ZWG", "ZiG", "Zimbabwe Gold", "Zimbabwe", Locale("en", "ZW")),
)

/** Format a number like the web app: "RM 1,234.50", JPY with 0 decimals. */
fun fmt(n: Double, cur: String): String {
    val c = CURRENCIES[cur] ?: CURRENCIES["MYR"]!!
    val sign = if (n < 0) "-" else ""
    val decimals = if (c.code == "JPY") 0 else 2
    val nf = NumberFormat.getNumberInstance(c.locale).apply {
        minimumFractionDigits = decimals
        maximumFractionDigits = decimals
    }
    return "${c.symbol} $sign${nf.format(abs(n))}"
}

/** Plain symbol for quick-amount chips, e.g. "RM5". */
fun symbol(cur: String): String = (CURRENCIES[cur] ?: CURRENCIES["MYR"]!!).symbol
