package com.ledger.app.ui.strings

/**
 * English strings for transient app messages — toasts and confirm dialogs raised from
 * the view model. Merged into `EN` by ui/Strings.kt.
 */
val APP_STRINGS: Map<String, String> = mapOf(
    "toast.corruptData" to "Some saved data ({keys}) couldn't be read. Sync is paused to protect it.",
    "toast.automatedEntriesAdded" to "Automated entries added.",
    "toast.invalidAmount" to "Enter a valid amount.",
    "toast.pickStartDate" to "Pick a start date.",
    "toast.automationAdded" to "Automation added.",
    "toast.automationRemoved" to "Automation removed.",
    "toast.restored" to "Restored.",
    "toast.actionUndo" to "Undo",
    "toast.invalidAmountPeriod" to "Enter a valid amount and period.",
    "toast.invalidBalance" to "Enter a valid balance.",
    "toast.budgetUpdated" to "Budget updated.",
    "toast.budgetSaved" to "Budget saved. Start tracking!",
    "toast.invalidTopUpAmount" to "Enter a valid top-up amount.",
    "toast.notEnoughForMove" to "Not enough balance — move at most {amount}.",
    "toast.movedToBudget" to "Moved {amount} from your balance to this month's budget.",
    "toast.toppedUp" to "Topped up {amount} — added to your monthly budget.",
    "toast.addedToBalance" to "Added {amount} to your balance.",
    "toast.nothingToReturn" to "Nothing to return — you haven't moved money to the budget. Please move some first.",
    "toast.returnTooMuch" to "Can't return more than the {amount} you moved to the budget.",
    "toast.returnedToBalance" to "Returned {amount} from your budget to your balance.",
    "toast.nothingToWithdraw" to "Nothing to withdraw — your balance is empty. Move money into it first.",
    "toast.notEnoughForWithdraw" to "Not enough balance — withdraw at most {amount}.",
    "toast.withdrewFromBalance" to "Withdrew {amount} from your balance.",
    "toast.transferRemoved" to "Transfer removed.",
    "toast.piggyCreated" to "Created {name}.",
    "toast.piggyRenamed" to "Piggy bank renamed.",
    "toast.invalidGoalAmount" to "Enter a valid goal amount.",
    "toast.savingsGoalSet" to "Savings goal set to {amount}.",
    "toast.savingsGoalCleared" to "Savings goal cleared.",
    "toast.notEnoughForAdd" to "Not enough balance — add at most {amount}.",
    "toast.addedToPiggy" to "Added {amount} to {name}.",
    "toast.goalComplete" to "Goal complete for {name}! 🎉",
    "toast.piggyEmpty" to "{name} is empty.",
    "toast.piggyBroken" to "Broke {name} — {amount} back to your balance.",
    "toast.cannotDeleteOnlyPiggy" to "Cannot delete the only piggy bank.",
    "toast.piggyDeleted" to "Deleted {name}.",
    "toast.loggedAbroad" to "Logged {amount} ≈ {home} in {category}.",
    "toast.logged" to "Logged {amount} in {category}.",
    "toast.spendUpdated" to "Spend updated.",
    "toast.spendRemoved" to "Spend removed.",
    "toast.duplicated" to "Duplicated {amount}.",
    "toast.enterCategoryName" to "Enter a category name.",
    "toast.invalidCategoryName" to "Invalid or duplicate name.",
    "toast.categoryAdded" to "Category \"{name}\" added.",
    "toast.cannotDeleteCategory" to "Can't delete — expenses use this category.",
    "toast.categoryRemoved" to "Category removed.",
    "toast.themeApplied" to "{name} theme applied.",
    "toast.themeReset" to "Theme reset.",
    "toast.tripEnded" to "Trip ended. Your travel spends are saved.",
    "confirm.endTripTitle" to "End this trip?",
    "confirm.endTripMsg" to "Your travel spends stay in History, tagged with the trip — nothing is deleted. You can start a new trip any time.",
    "toast.restoredPreviousTheme" to "Restored previous theme.",
    "toast.paperThemeApplied" to "Paper theme applied.",
    "toast.monoThemeApplied" to "Mono theme applied.",
    "toast.cardOrderReset" to "Card order reset.",
    "toast.chooseImageFile" to "Please choose an image file.",
    "toast.wallpaperSet" to "Wallpaper set.",
    "toast.wallpaperSetFailed" to "Couldn't set wallpaper.",
    "toast.wallpaperRemoved" to "Wallpaper removed.",
    "toast.receiptAttached" to "Receipt attached.",
    "toast.receiptReadFailed" to "Couldn't read that image.",
    "toast.remindersOn" to "Daily reminders turned on.",
    "toast.remindersOff" to "Reminders turned off.",
    "toast.reminderTimeUpdated" to "Reminder time updated.",
    "toast.budgetAlertsEnabled" to "Budget alert warnings enabled.",
    "toast.budgetAlertsDisabled" to "Budget alerts disabled.",
    "toast.testNotificationSent" to "Test notification sent.",
    "toast.glassEnabled" to "Liquid glass enabled.",
    "toast.glassDisabled" to "Liquid glass disabled.",
    "toast.allDataCleared" to "All data cleared.",
    "toast.restoredEntries" to "Restored {count} entries.",
    "toast.syncedFromCloud" to "Synced from cloud.",
    "toast.signInToSync" to "Sign in with Google to sync.",
    "toast.syncing" to "Syncing...",
    "toast.syncNotConfigured" to "Sync isn't configured yet — see the Sync section in settings.",
    "toast.syncError" to "Sync error",
    "toast.syncSubscribeFailed" to "Sync subscribe failed",
    "toast.syncPushFailed" to "Sync push failed",
    "toast.firebaseLoadFailed" to "Couldn't load Firebase — check your internet connection and reload.",
    "toast.signedIn" to "Signed in — syncing is on.",
    "toast.signInCancelled" to "Sign-in cancelled.",
    "toast.firebaseAndroidAppMissing" to "Firebase: Add Android app (com.ledger.app) in Firebase Console, or set androidAppId in FirebaseConfig.kt.",
    "toast.signInFailed" to "Sign-in failed.",
    "toast.signedOut" to "Signed out. Changes stay on this device.",
    "toast.signOutFailed" to "Sign out failed.",
    "toast.importInvalidBackup" to "Not a valid ledger backup.",
    "toast.importReadFailed" to "Couldn't read that file. ({detail})",
    "toast.monthlyBudget" to "Monthly budget",
    "toast.thisMonth" to "This month",
    "toast.budgetExceeded" to "Budget exceeded",
    "toast.budgetAlert80" to "Budget alert — 80%",
    "toast.budgetUsed" to "{scope}: {spent} of {budget} used.",
    "confirm.breakPiggyTitle" to "Break {name}?",
    "confirm.breakPiggyMsg" to "All {amount} moves back to your balance.",
    "confirm.deletePiggyTitle" to "Delete {name}?",
    "confirm.deletePiggyWithSavings" to "All {amount} saved in this piggy bank will move back to your balance.",
    "confirm.deletePiggy" to "Are you sure you want to delete {name}?",
    "confirm.clearAllTitle" to "Delete everything?",
    "confirm.clearAllMsg" to "This removes all logged expenses, budget settings, and preferences. Download a backup first if you want to keep your data.",
)
