package com.ledger.app.ui.strings

/**
 * English strings for the dashboard cards. Merged into `EN` by ui/Strings.kt.
 * Keys are shared verbatim with the web app (see src/lib/strings/cards.js).
 */
val CARD_STRINGS: Map<String, String> = mapOf(
    /* Breakdown */
    "card.breakdown.title" to "Category breakdown",
    "card.breakdown.rangePeriod" to "Period",
    "card.breakdown.range7d" to "7d",
    "card.breakdown.rangeMonth" to "Month",
    "card.breakdown.rangeAll" to "All",
    "card.breakdown.rangeCustom" to "Custom",
    "card.breakdown.save" to "Save",
    "card.breakdown.cancel" to "Cancel",
    "card.breakdown.budgets" to "Budgets",
    "card.breakdown.thisMonth" to "This month",
    "card.breakdown.showing" to "Showing {month}",
    "card.breakdown.from" to "From",
    "card.breakdown.startDate" to "Start date",
    "card.breakdown.to" to "To",
    "card.breakdown.maxDate" to "Max date",
    "card.breakdown.totalSpent" to "Total spent",
    "card.breakdown.pctAllowance" to "% of allowance",
    "card.breakdown.vs" to "vs {amount} · {days}d",
    "card.breakdown.avgPerDay" to "Avg spending/day",
    "card.breakdown.txns" to "Txns",
    "card.breakdown.biggest" to "Biggest",
    "card.breakdown.noSpending" to "no spending",
    "card.breakdown.spent" to "spent",
    "card.breakdown.noLimit" to "No limit",
    "card.breakdown.budgetSuffix" to " / {amount}",

    /* Trend */
    "card.trend.title" to "Spending trend",
    "card.trend.titleHeatmap" to "Spending heatmap",
    "card.trend.range7d" to "7d",
    "card.trend.range14d" to "14d",
    "card.trend.range30d" to "30d",
    "card.trend.range90d" to "90d",
    "card.trend.range1y" to "1y",
    "card.trend.fullMonth" to "Full month",
    "card.trend.total" to "Total",
    "card.trend.pickOne" to "Pick one or more — each category draws its own line.",
    "card.trend.allowance" to "Allowance ({amount})",

    /* Piggy bank */
    "card.piggy.title" to "Piggy banks",
    "card.piggy.editGoal" to "Edit goal",
    "card.piggy.setGoal" to "Set goal",
    "card.piggy.customize" to "Customize",
    "card.piggy.defaultName" to "Piggy bank",
    "card.piggy.new" to "New",
    "card.piggy.createTitle" to "Create new piggy bank",
    "card.piggy.namePlaceholder" to "Name (e.g. Vacation fund)",
    "card.piggy.targetPlaceholder" to "Target goal (e.g. 500)",
    "card.piggy.cancel" to "Cancel",
    "card.piggy.create" to "Create",
    "card.piggy.renamePlaceholder" to "Name",
    "card.piggy.rename" to "Rename",
    "card.piggy.delete" to "Delete",
    "card.piggy.saved" to "Saved",
    "card.piggy.targetLabel" to "Goal: {amount}",
    "card.piggy.goalComplete" to "Goal complete! 🎉",
    "card.piggy.toGo" to "{amount} to go",
    "card.piggy.setGoalHint" to "Set a goal to track progress",
    "card.piggy.add" to "Add",
    "card.piggy.break" to "Break",
    "card.piggy.customizeTitle" to "Customize {name}",
    "card.piggy.fallbackName" to "Piggy",
    "card.piggy.pictureIcon" to "Picture / Icon",
    "card.piggy.depositSound" to "Deposit sound",
    "card.piggy.soundCoin" to "Coin",
    "card.piggy.soundChime" to "Chime",
    "card.piggy.soundMute" to "Mute",

    /* Automations */
    "card.auto.title" to "Automations",
    "card.auto.runNow" to "Run now",
    "card.auto.spending" to "Spending",
    "card.auto.topUpBudget" to "Top up budget",
    "card.auto.topUpBalance" to "Top up balance",
    "card.auto.amount" to "Amount",
    "card.auto.freqDaily" to "Daily",
    "card.auto.freqWeekly" to "Weekly",
    "card.auto.freqMonthly" to "Monthly",
    "card.auto.notePlaceholder" to "Note (optional)",
    "card.auto.add" to "Add",
    "card.auto.toBudget" to "to budget",
    "card.auto.toBalance" to "to balance",
    "card.auto.started" to "Started {date} · {next}",
    "card.auto.pause" to "Pause",
    "card.auto.resume" to "Resume",
    "card.auto.remove" to "Remove",
    "card.auto.emptyTitle" to "Repeating entries appear here.",
    "card.auto.emptyDesc" to "e.g. rent on the 1st, salary on the 25th.",

    /* Data & backup */
    "card.backup.title" to "Data & backup",
    "card.backup.downloaded" to "Backup downloaded.",
    "card.backup.writeBackupFailed" to "Couldn't write the backup file.",
    "card.backup.csvExported" to "CSV exported.",
    "card.backup.writeCsvFailed" to "Couldn't write the CSV file.",
    "card.backup.readFailed" to "Couldn't read that file.",
    "card.backup.backupJson" to "Backup (JSON)",
    "card.backup.exportCsv" to "Export CSV",
    "card.backup.loadBackup" to "Load backup",
    "card.backup.editBudget" to "Edit budget",
    "card.backup.moveMoney" to "Move money",
    "card.backup.topUp" to "Top up",
    "card.backup.cloudActive" to "Cloud sync is active ({who}).",
    "card.backup.signedIn" to "signed in",
    "card.backup.localOnly" to "Your data is stored locally on this device. Sign in to cloud sync in Settings to sync across devices.",
    "card.backup.clearAll" to "Clear all",

    /* Monthly insights */
    "card.insights.title" to "Monthly insights",
    "card.insights.emptyTitle" to "Insights appear as you spend.",
    "card.insights.emptyDesc" to "Compare this month to last, your pace, and best/worst days.",
    "card.insights.thisMonth" to "This month",
    "card.insights.noChange" to "no change",
    "card.insights.vsLastMonth" to "vs {amount} last month",
    "card.insights.avgPerDay" to "Average per day",
    "card.insights.daySoFar" to "{days} day so far",
    "card.insights.daysSoFar" to "{days} days so far",
    "card.insights.biggestChange" to "Biggest change",
    "card.insights.deltaVsLastMonth" to "{sign}{amount} vs last month",
    "card.insights.projected" to "Projected month-end",
    "card.insights.leftAtPace" to "{amount} left at pace",
    "card.insights.overAtPace" to "{amount} over at pace",
    "card.insights.basedOnPace" to "based on this month's pace",
    "card.insights.bestDay" to "Best day",
    "card.insights.worstDay" to "Worst day",

    /* Streak */
    "card.streak.title" to "Streak",
    "card.streak.current" to "Current streak",
    "card.streak.best" to "Best streak",
    "card.streak.day" to "{n} day",
    "card.streak.days" to "{n} days",
    "card.streak.dayWord" to "day",
    "card.streak.daysWord" to "days",
    "card.streak.loggedToday" to "Logged today",
    "card.streak.notLoggedToday" to "Not logged yet today",
    "card.streak.hint" to "Log a spend every day to keep your streak alive.",
    "card.streak.graceOn" to "{n} grace day(s) in play.",
)
