package com.ledger.app.ui.strings

/**
 * English strings for the app shell: nav, drawers, setup, locks and toasts.
 * Merged into `EN` by ui/Strings.kt. Keys are shared verbatim with the web app
 * (see src/lib/strings/shell.js).
 */
val SHELL_STRINGS: Map<String, String> = mapOf(
    /* Nav, card order and shared shell chrome */
    "app.nav.logSpend" to "Log spend",
    "app.nav.settings" to "Settings",
    "app.close" to "Close",
    "app.moveUp" to "Move up",
    "app.moveDown" to "Move down",
    "app.cardLabel.breakdown" to "Category breakdown",
    "app.cardLabel.insights" to "Monthly insights",
    "app.cardLabel.trend" to "Spending trend",
    "app.cardLabel.streak" to "Streak",
    "app.cardLabel.auto" to "Automations",
    "app.cardLabel.piggy" to "Piggy bank",
    "app.cardLabel.backup" to "Data & backup",
    "app.tagline" to "Personal budget",

    /* Shared controls */
    "app.prevMonth" to "Previous month",
    "app.nextMonth" to "Next month",
    "app.pickColor" to "Pick a color",
    "app.hue" to "Hue",
    "app.saturation" to "Saturation",
    "app.brightness" to "Brightness",
    "app.ok" to "OK",
    "app.cancel" to "Cancel",
    "app.confirm" to "Confirm",

    /* Shared sign-in / import messages */
    "app.signInWithGoogle" to "Sign in with Google",
    "app.signInCancelled" to "Sign-in cancelled.",
    "app.googleIdTokenError" to "Couldn't retrieve Google ID token.",
    "app.googleSignInError" to "Google sign-in error ({code}): {message}",
    "app.couldntReadFile" to "Couldn't read that file.",

    /* Dashboard hero */
    "screen.dashboard.slideHint" to "Slide across the bars to see each day's spending.",
    "screen.dashboard.noSpendingYet" to "no spending yet",
    "screen.dashboard.spent" to "spent {amount}",
    "screen.dashboard.perDays" to "{amount} / {days}d",
    "screen.dashboard.daysOver" to "{days}d over",
    "screen.dashboard.onTrack" to "On track",
    "screen.dashboard.nearLimit" to "Near limit",
    "screen.dashboard.overToday" to "Over today",

    /* App lock */
    "lock.locked" to "Ledger is locked",
    "lock.unlockHint" to "Unlock to continue.",
    "lock.unlock" to "Unlock",

    /* Setup */
    "setup.introBalance" to "Set a bank balance, track your daily allowance,\nand bank whatever you don't spend each day.",
    "setup.intro" to "Set your budget, track your daily allowance,\nand carry over what you don't spend.",
    "setup.budgetAmount" to "Budget amount",
    "setup.startingBankBalance" to "Starting bank balance",
    "setup.startingBankBalanceDesc" to "The money you have right now — you can move it into your budget whenever you need it.",
    "setup.startTracking" to "Start tracking",
    "setup.or" to "or",
    "setup.restore" to "Restore from a backup",
    "setup.restoreDesc" to "Already have a ledger-backup .json file or cloud account? Load it to pick up right where you left off.",

    /* Drawers */
    "drawer.budgetSettings" to "Budget settings",
    "drawer.bankBalance" to "Bank balance",
    "drawer.bankBalanceDesc" to "Your bank balance. Transfers to the budget come out of this; leftover allowance is banked back into it.",
    "drawer.realignFirst" to "Realign to 1st of this month",
    "drawer.saveChanges" to "Save changes",
    "drawer.moneyTitle" to "Money",
    "drawer.topUpBudgetTitle" to "Top up budget",
    "drawer.toBudget" to "To budget",
    "drawer.toBalance" to "To balance",
    "drawer.addBalance" to "Add balance",
    "drawer.withdrawBalance" to "Withdraw balance",
    "drawer.balance" to "Balance",
    "drawer.after" to "After",
    "drawer.amountToAdd" to "Amount to add",
    "drawer.amountToMoveToBudget" to "Amount to move to budget",
    "drawer.amountToReturn" to "Amount to return to balance",
    "drawer.amountToWithdraw" to "Amount to withdraw",
    "drawer.noteExampleBonus" to "e.g. bonus, birthday money",
    "drawer.noteExampleReturn" to "e.g. took out the extra food money",
    "drawer.noteExampleExtra" to "e.g. extra cash for food",
    "drawer.descAddFunds" to "Added to your total monthly budget — your daily allowance rises for the rest of the period.",
    "drawer.descToBudget" to "Moved out of your balance into this month's budget — your daily allowance rises for the rest of the period.",
    "drawer.descToBalance" to "Moves money from your budget back to your balance — you can only take back what you moved in.",
    "drawer.descWithdraw" to "Removes money from your balance, e.g. to spend it elsewhere — it stays gone even if you stay under budget.",
    "drawer.descAddBalance" to "Money you add from outside the app — it raises your balance and is protected from spending.",
    "drawer.recentTransfers" to "Recent transfers",
    "drawer.recentTopUps" to "Recent top-ups",
    "drawer.addFunds" to "Add funds",
    "drawer.withdraw" to "Withdraw",
    "drawer.addToBalance" to "Add to balance",
    "drawer.toggleLightDark" to "Toggle light / dark",
    "drawer.colorBackground" to "Background",
    "drawer.colorSurface" to "Surface",
    "drawer.colorAccent" to "Accent",
    "drawer.colorAccentText" to "Accent text",
    "drawer.colorText" to "Text",
    "drawer.positiveUnder" to "Positive / Under",
    "drawer.warningNear" to "Warning / Near",
    "drawer.negativeOver" to "Negative / Over",
    "drawer.wallpaper" to "Wallpaper",
    "drawer.wallpaperPreview" to "Wallpaper preview",
    "drawer.backgroundDim" to "Background dim",
    "drawer.blurIntensity" to "Blur intensity",
    "drawer.replacePhoto" to "Replace photo",
    "drawer.setPhotoWallpaper" to "Set photo wallpaper",
    "drawer.wallpaperDesc" to "Upload a custom photo for your dashboard background.",
    "drawer.liquidGlass" to "Liquid glass",
    "drawer.glassCards" to "Liquid glass cards",
    "drawer.glassCardsDesc" to "Give the dashboard cards a frosted, translucent glass look over your wallpaper.",
    "drawer.glassScreens" to "Liquid glass screens",
    "drawer.glassScreensDesc" to "Give the Log a spend and History drawers a frosted glass backdrop.",
    "drawer.glassInside" to "Glass the inside cards",
    "drawer.glassInsideDesc" to "Instead of the backdrop, make the Log a spend and History cards themselves liquid glass (on a flat light background).",
    "drawer.gaussianBlur" to "Gaussian blur",
    "drawer.transparency" to "Transparency",
    "drawer.subCardOpacity" to "Sub-card opacity",
    "drawer.refractionHeight" to "Refraction height",
    "drawer.refractionAmount" to "Refraction amount",
    "drawer.chromaticAmount" to "Chromatic aberration amount",
    "drawer.chromaDesc" to "Chrom. aberration creates a prismatic RGB edge on the refraction; 0% = off. Applied to the bottom navigation pill and the dashboard cards. Lower transparency = more frosted. Sub-card opacity sets how solid the panels inside the cards are (0% = fully clear, 100% = solid).",
    "drawer.widgets.title" to "Home-screen widgets",
    "drawer.widgets.desc" to "Widgets can follow a light or dark theme, independently of the app.",
    "drawer.widgets.theme" to "Widget theme",
    "drawer.widgets.dark" to "Dark",
    "drawer.widgets.light" to "Light",
    "drawer.screenEdges" to "Screen edges",
    "drawer.edgeBlurDesc" to "Soften the top and bottom of the screen as content scrolls under them. Off gives a crisp, unmasked edge.",
    "drawer.cardLayoutDesc" to "Use the arrow buttons on each card to rearrange the order.",
    "drawer.resetCardOrder" to "Reset card order",
    "drawer.preview" to "Preview",
    "drawer.ringThickness" to "Ring thickness",
    "drawer.segmentGap" to "Segment gap",
    "drawer.trendStyle" to "Trend style",
    "drawer.lineChart" to "Line chart",
    "drawer.heatmap" to "Heatmap",
    "drawer.heatmapColors" to "Heatmap colors",
    "drawer.emptyDays" to "Empty days",
    "drawer.level" to "Level {n}",
    "drawer.none" to "none",
    "drawer.emptyDaysDesc" to "\"Empty days\" is the base cell color — set to none for the default transparent look.",
    "drawer.categoryColors" to "Category colors",
    "drawer.categoryColorsDesc" to "Controls pie chart, bar chart, and badges.",
    "drawer.yourCategories" to "Your categories",
    "drawer.addCategory" to "Add category",
    "drawer.categoryNamePlaceholder" to "Name (e.g. Health)",
    "drawer.categoryGlyphDesc" to "Use short symbols (◇ ★ ♥ ● ▲ ◐) for the icon.",
    "drawer.overspendFromBalance" to "Overspends come from balance",
    "drawer.overspendFromBalanceDesc" to "When you spend more than a day's allowance, take it out of your bank balance. Off = the overspend is covered by the monthly budget.",
    "drawer.budget" to "Budget",
    "drawer.security" to "Security",
    "drawer.appLockDesc" to "Require your fingerprint, face, or device PIN/pattern every time Ledger opens.",
    "drawer.notifications" to "Notifications & reminders",
    "drawer.dailyReminder" to "Daily spend reminder",
    "drawer.dailyReminderDesc" to "Get an evening reminder to log your daily expenses.",
    "drawer.reminderTime" to "Reminder time",
    "drawer.time1900" to "7:00 PM (19:00)",
    "drawer.time2000" to "8:00 PM (20:00)",
    "drawer.time2100" to "9:00 PM (21:00)",
    "drawer.time2200" to "10:00 PM (22:00)",
    "drawer.time1200" to "12:00 PM (12:00)",
    "drawer.time1800" to "6:00 PM (18:00)",
    "drawer.budgetAlertWarnings" to "Budget alert warnings",
    "drawer.budgetAlertWarningsDesc" to "Notify when spending exceeds your daily allowance.",
    "drawer.sendTestReminder" to "Send test reminder",
    "drawer.signedIn" to "Signed in",
    "drawer.syncErrorRetry" to "Sync error — will retry automatically",
    "drawer.accountId" to "Account ID {id}…",
    "drawer.lastSynced" to "Last synced {time}",
    "drawer.signOut" to "Sign out",
    "drawer.syncDescSignedIn" to "Your budget, balance, expenses, transfers, categories, theme and preferences sync automatically. The newest copy wins — edits from any device appear here.",
    "drawer.syncDescSignIn" to "Sign in to back up and sync your budget across devices with your Google account. Your data stays private — only you can read your copy.",
    "drawer.syncNeedsFirebase" to "Sync is ready but needs a Firebase project. Open FirebaseConfig.kt, find the FIREBASE_CONFIG values, and paste your Firebase project config. Then enable Google sign-in and create a Firestore database with security rules.",
    "drawer.streaksDesc" to "Forgive skipped days inside your logging streak — the run stays alive instead of resetting.",
    "drawer.oneDay" to "1 day",
    "drawer.twoDays" to "2 days",
    "drawer.languageDesc" to "Menus, cards and settings are translated. Some longer passages stay in English for now.",
    "drawer.travelDesc" to "Log spends in a foreign currency. Each entry is converted to your home currency and tagged “travel” — the home page becomes your trip page.",
    "drawer.travelOn" to "On — the home page shows your trip instead of the dashboard.",
    "drawer.travelOff" to "Off — the normal dashboard.",
    "drawer.ratePlaceholder" to "Home units per 1 foreign unit",
    "drawer.rateDesc" to "1 {foreign} = {home}. Entries are converted at this rate as you log them.",
    "drawer.shortcutLogSpendDesc" to "Tap the Log spend button",
    "drawer.shortcutHistoryDesc" to "Tap the History button",
    "drawer.lightDark" to "Light / dark",
    "drawer.shortcutLightDarkDesc" to "Themes tab → Toggle light / dark",
    "drawer.resetTheme" to "Reset theme to default",

    /* Computed labels — assembled outside the composables (LedgerViewModel) */
    "hero.labelBalance" to "Balance",
    "hero.labelAvailable" to "Available today",
    "card.auto.paused" to "Paused",
    "card.auto.dueToday" to "Due today",
    "card.auto.tomorrow" to "Tomorrow",
    "card.auto.inDays" to "in {n}d",
    "card.breakdown.rangeLabelPeriod" to "this budget period",
    "card.breakdown.rangeLabelWeek" to "the last 7 days",
    "card.breakdown.rangeLabelMonth" to "this calendar month",
    "card.breakdown.rangeLabelAll" to "all logged history",
    "card.breakdown.rangeLabelCustom" to "the selected range",

    /* Home-screen widgets */
    "widget.setupValue" to "Set up your budget",
    "widget.setupNote" to "Open the app to begin",
    "widget.overToday" to "Over today's allowance",
    "widget.ofAmount" to "of {amount}",
    "widget.budgetDetail" to "of {amount} · {n}% used",
    "widget.piggyDetail" to "of {amount} · {n}%",
    "widget.noGoal" to "No goal set",
    "widget.streakDaysOne" to "🔥 {n} day",
    "widget.streakDaysMany" to "🔥 {n} days",
    "widget.streakStart" to "Log a spend to start",
    "widget.streakLoggedToday" to "Logged today",
    "widget.streakNotLogged" to "Not logged yet today",
    "widget.other" to "Other",
    "widget.pieEmpty" to "No spending yet this period",
    "widget.periodSpent" to "{amount} this period",

    /* Shared labels used by more than one surface. */
    "common.edit" to "Edit",
    "common.delete" to "Delete",
    "common.duplicate" to "Duplicate",
    "common.removeTransfer" to "Remove transfer",
    "common.receipt" to "Receipt",
    "palette.title" to "Command palette",
    "history.startDate" to "Start date",
    "history.maxDate" to "Max date",
    "chart.less" to "Less",
    "chart.more" to "More",
    "chart.spent" to "{amount} spent",

    /* Notifications. */
    "notif.channelName" to "Ledger Reminders",
    "notif.channelDesc" to "Daily spend reminders and budget alerts",
    "notif.dailyTitle" to "Ledger — Daily Log",
    "notif.dailyBody" to "Did you spend anything today? Tap to log your expenses.",
    "notif.dailyBodyLong" to "Did you spend anything today? Keep your budget and allowances accurate by logging your daily expenses.",
    "notif.dailyBodyStreak" to "You're on a {n}-day streak. Did you spend anything today?",
    "notif.dailyBodyLongStreak" to "You're on a {n}-day streak. Keep your budget and allowances accurate by logging today's spend.",
    "notif.graceTitle" to "Your streak needs you today",
    "notif.graceBody" to "You missed yesterday — log a spend today or your {n}-day streak ends.",
    "notif.graceBodyLong" to "You missed yesterday, so today is the last day your grace period can cover. Log a spend to keep your {n}-day streak alive.",
    "log.welcomeFirst" to "Welcome — log your first spend to start tracking.",
    "tab.travel" to "Travel",
    "travel.homeCurrency" to "Home currency",
    "travel.homeCurrencyDesc" to "Your own currency. Budgets, statistics and the hero are all reported in it.",
    "travel.rateAuto" to "Sync rate automatically",
    "travel.rateAutoDesc" to "Refresh the rate from the ECB reference rates when the trip starts or either currency changes.",
    "travel.refreshRate" to "Refresh rate now",
    "travel.rateFetching" to "Fetching the latest rate…",
    "travel.rateAsOf" to "Rate as of {date}",
    "travel.rateUpdated" to "Rate updated.",
    "travel.rateFailed" to "Could not reach the rate service. Keeping the saved rate.",
    "travel.rateNote" to "Home units per 1 {foreign}. Applied to new entries only — logged spends keep the amounts they were recorded with.",
    "travel.currenciesUsed" to "Currencies logged on this trip",
    "travel.currenciesUsedDesc" to "Switching the trip currency never rewrites entries you have already logged.",
    "travel.noCurrencies" to "Nothing logged on this trip yet.",
    "travel.currencies" to "{n} currencies",
    "travel.homeCurrencyIs" to "Reported in {home}",
    "travel.ratePrivacy" to "Rate lookups send only the two currency codes to the ECB reference service.",
)
