/* English strings for the dashboard cards. Merged into EN by src/lib/i18n.js.
   Keys are shared verbatim with the Android app (see ui/strings/CardStrings.kt). */
export default {
  /* Category breakdown */
  'card.breakdown.title': 'Category breakdown',
  'card.breakdown.save': 'Save',
  'card.breakdown.cancel': 'Cancel',
  'card.breakdown.budgets': 'Budgets',
  'card.breakdown.rangePeriod': 'Period',
  'card.breakdown.range7d': '7d',
  'card.breakdown.rangeMonth': 'Month',
  'card.breakdown.rangeAll': 'All',
  'card.breakdown.rangeCustom': 'Custom',
  'card.breakdown.from': 'From',
  'card.breakdown.to': 'To',
  'card.breakdown.totalSpent': 'Total spent',
  'card.breakdown.pctAllowance': '% of allowance',
  'card.breakdown.vs': 'vs {amount} · {days}d',
  'card.breakdown.avgPerDay': 'Avg spending/day',
  'card.breakdown.top': 'Top',
  'card.breakdown.txns': 'Txns',
  'card.breakdown.biggest': 'Biggest',
  'card.breakdown.spent': 'spent',
  'card.breakdown.sliceTitle': '{label}: {amount} ({pct}%)',
  'card.breakdown.noLimit': 'No limit',

  /* Spending trend */
  'card.trend.title': 'Spending trend',
  'card.trend.heatmapTitle': 'Spending heatmap',
  'card.trend.days': '{n}d',
  'card.trend.year': '1y',
  'card.trend.mon': 'Mon',
  'card.trend.tue': 'Tue',
  'card.trend.wed': 'Wed',
  'card.trend.thu': 'Thu',
  'card.trend.fri': 'Fri',
  'card.trend.sat': 'Sat',
  'card.trend.sun': 'Sun',
  'card.trend.cellTitle': '{date} · Spent {amount}',
  'card.trend.less': 'Less',
  'card.trend.more': 'More',
  'card.trend.totalSpent': '{amount} spent',
  'card.trend.total': 'Total',
  'card.trend.pickHint': 'Pick one or more — each category draws its own line.',
  'card.trend.allowance': 'Allowance ({amount})',

  /* Piggy banks */
  'card.piggy.title': 'Piggy banks',
  'card.piggy.defaultName': 'Piggy bank',
  'card.piggy.editGoal': 'Edit goal',
  'card.piggy.setGoal': 'Set goal',
  'card.piggy.settingsTitle': 'Picture & sound settings',
  'card.piggy.new': 'New',
  'card.piggy.createTitle': 'Create new piggy bank',
  'card.piggy.namePlaceholder': 'Name (e.g. Vacation fund)',
  'card.piggy.targetPlaceholder': 'Target goal (e.g. 500)',
  'card.piggy.create': 'Create',
  'card.piggy.cancel': 'Cancel',
  'card.piggy.saveName': 'Save name',
  'card.piggy.renameTitle': 'Rename piggy bank',
  'card.piggy.deleteTitle': 'Delete piggy bank',
  'card.piggy.saveGoal': 'Save goal',
  'card.piggy.saved': 'Saved',
  'card.piggy.noGoal': 'No goal yet',
  'card.piggy.goalComplete': 'Goal complete! 🎉',
  'card.piggy.toGo': '{amount} to go',
  'card.piggy.setGoalHint': 'Set a goal and watch it fill up.',
  'card.piggy.addFunds': 'Add funds',
  'card.piggy.break': 'Break',
  'card.piggy.deposit': 'Deposit',
  'card.piggy.customize': 'Customize {name}',
  'card.piggy.pictureLabel': 'Picture / Texture',
  'card.piggy.customPicture': 'Custom picture',
  'card.piggy.resetPicture': 'Reset picture',
  'card.piggy.depositSound': 'Deposit Sound',
  'card.piggy.soundCoin': 'Coin',
  'card.piggy.soundChime': 'Chime',
  'card.piggy.soundCustom': 'Custom',
  'card.piggy.soundMute': 'Mute',
  'card.piggy.uploadFirst': 'Upload a custom sound file first.',
  'card.piggy.uploadSound': 'Upload sound',
  'card.piggy.removeSound': 'Remove sound',
  'card.piggy.previewSound': 'Preview sound',
  'card.piggy.invalidGoal': 'Enter a valid goal amount.',
  'card.piggy.invalidAmount': 'Enter a valid amount.',
  'card.piggy.newName': 'Piggy #{n}',
  'card.piggy.imageTooLarge': 'Image file is too large (max 2MB).',
  'card.piggy.pictureUpdated': 'Custom picture updated.',
  'card.piggy.audioTooLarge': 'Audio file is too large (max 2MB).',
  'card.piggy.soundUploaded': 'Custom sound uploaded.',

  /* Automations */
  'card.auto.title': 'Automations',
  'card.auto.runNow': 'Run now',
  'card.auto.runNowTitle': 'Materialize any due entries now',
  'card.auto.typeExpense': 'Spending',
  'card.auto.typeBudget': 'Top up budget',
  'card.auto.typeBalance': 'Top up balance',
  'card.auto.amountPlaceholder': 'Amount',
  'card.auto.notePlaceholder': 'Note (optional)',
  'card.auto.add': 'Add',
  'card.auto.toBudget': 'to budget',
  'card.auto.toBalance': 'to balance',
  'card.auto.started': 'Started {date} · {next}',
  'card.auto.pause': 'Pause',
  'card.auto.resume': 'Resume',
  'card.auto.removeTitle': 'Remove',
  'card.auto.empty': 'Repeating entries appear here.',
  'card.auto.emptySub': 'e.g. rent on the 1st, salary on the 25th.',
  'card.auto.freqDaily': 'Daily',
  'card.auto.freqWeekly': 'Weekly',
  'card.auto.freqMonthly': 'Monthly',

  /* Data & backup */
  'card.backup.title': 'Data & backup',
  'card.backup.backupJson': 'Backup (JSON)',
  'card.backup.exportCsv': 'Export CSV',
  'card.backup.loadBackup': 'Load backup',
  'card.backup.editBudget': 'Edit budget',
  'card.backup.moveMoney': 'Move money',
  'card.backup.topUp': 'Top up',
  'card.backup.localNote': 'Your data is stored locally in your browser. Nothing is sent anywhere.',
  'card.backup.clearAll': 'Clear all',

  /* Monthly insights */
  'card.insights.title': 'Monthly insights',
  'card.insights.dayCount': '{elapsed}/{total}d',
  'card.insights.thisMonth': 'This month',
  'card.insights.lastMonth': 'Last month',
  'card.insights.change': 'Change',
  'card.insights.avgPerDay': 'Avg/day',
  'card.insights.projected': 'Projected month-end',
  'card.insights.vsLastMonth': 'vs last month',
  'card.insights.over': 'over',
  'card.insights.under': 'under',
  'card.insights.biggestChange': 'Biggest change',
  'card.insights.bestDay': 'Best day',
  'card.insights.worstDay': 'Worst day',

  /* Streak */
  'card.streak.title': 'Streak',
  'card.streak.current': 'Current streak',
  'card.streak.best': 'Best streak',
  'card.streak.day': '{n} day',
  'card.streak.days': '{n} days',
  'card.streak.dayWord': 'day',
  'card.streak.daysWord': 'days',
  'card.streak.loggedToday': 'Logged today',
  'card.streak.notLoggedToday': 'Not logged yet today',
  'card.streak.hint': 'Log a spend every day to keep your streak alive.',
  'card.streak.graceOn': '{n} grace day(s) in play.',
};
