/* English strings for the app shell: nav, drawers, setup, palette, dialogs, locks and
   toasts. Merged into EN by src/lib/i18n.js. Keys are shared verbatim with the Android
   app (see ui/strings/ShellStrings.kt). */
export default {
  /* Card-order labels & app chrome (App.jsx) */
  'app.cardLabel.log': 'Log a spend',
  'app.cardLabel.breakdown': 'Category breakdown',
  'app.cardLabel.trend': 'Spending trend',
  'app.cardLabel.history': 'History',
  'app.cardLabel.insights': 'Monthly insights',
  'app.cardLabel.streak': 'Streak',
  'app.cardLabel.auto': 'Automations',
  'app.cardLabel.piggy': 'Piggy bank',
  'app.cardLabel.backup': 'Data & backup',
  'app.dragToReorder': 'Drag to reorder',
  'app.moveUp': 'Move up',
  'app.moveDown': 'Move down',
  'app.badgeOver': '● Over today',
  'app.badgeNear': '● Near limit',
  'app.badgeOn': '● On track',
  'app.errorTitle': 'Something went wrong',
  'app.errorDesc': 'Usually caused by a corrupt synced copy — reloading usually fixes it. If it keeps happening, reset local data (your cloud copy is preserved).',
  'app.errorReload': 'Reload',
  'app.errorReset': 'Reset local data & reload',
  'app.receiptAlt': 'Receipt',

  /* Customize drawer — shared */
  'drawer.cancel': 'Cancel',
  'drawer.remove': 'Remove',

  /* Customize drawer — Theme tab */
  'drawer.theme.backgroundDim': 'Background dim',
  'drawer.theme.replace': 'Replace',
  'drawer.theme.uploadWallpaper': 'Upload a photo or video',
  'drawer.theme.wallpaperDesc': 'Static images or short looping video clips (MP4/WebM). Large files may not survive a reload due to browser storage limits.',
  'drawer.theme.weatherNone': 'None',
  'drawer.theme.weatherRain': 'Rain',
  'drawer.theme.weatherSnow': 'Snow',
  'drawer.theme.effectSpeed': 'Effect speed',
  'drawer.theme.uiBlur': 'UI blur',
  'drawer.theme.uiTransparency': 'UI transparency',
  'drawer.theme.backgroundBlur': 'Background blur',
  'drawer.theme.colorBackground': 'Background',
  'drawer.theme.colorSurface': 'Surface',
  'drawer.theme.colorAccent': 'Accent',
  'drawer.theme.colorAccentText': 'Accent text',
  'drawer.theme.colorText': 'Text',
  'drawer.theme.statusPositive': 'Positive / Under',
  'drawer.theme.statusWarning': 'Warning / Near',
  'drawer.theme.statusNegative': 'Negative / Over',
  'drawer.theme.removeFont': 'Remove font',
  'drawer.theme.fontPlaceholder': 'Any Google Font, e.g. Bebas Neue',
  'drawer.theme.fontAdd': 'Add',
  'drawer.theme.fontDesc': 'Type any font name from fonts.google.com — it loads instantly and is remembered.',
  'drawer.theme.panelDesc': 'Skin every card with your own image — like a nameplate or sign texture wrapping the whole card.',
  'drawer.theme.panelStrength': 'Panel strength',
  'drawer.theme.uploadImage': 'Upload an image',
  'drawer.theme.layoutDesc': 'Drag the grip, or use the arrow buttons, on any card to rearrange the order.',
  'drawer.theme.resetCardOrder': 'Reset card order',
  'drawer.theme.catShow': 'Show desktop cat',
  'drawer.theme.catDesc': 'A little cat that chases your cursor.',
  'drawer.theme.catClassic': 'Classic',
  'drawer.theme.catCustomColor': 'Custom color',

  /* Customize drawer — Chart tab */
  'drawer.chart.pieTitle': 'Pie chart',
  'drawer.chart.ringThickness': 'Ring thickness',
  'drawer.chart.segmentGap': 'Segment gap',
  'drawer.chart.trendStyle': 'Trend style',
  'drawer.chart.line': 'Line chart',
  'drawer.chart.heatmap': 'Heatmap',
  'drawer.chart.heatmapColors': 'Heatmap colors',
  'drawer.chart.emptyDays': 'Empty days',
  'drawer.chart.level': 'Level {n}',
  'drawer.chart.heatDesc': '"Empty days" is the base cell color — set to none for the default transparent look.',
  'drawer.chart.categoryColors': 'Category colors',
  'drawer.chart.categoryColorsDesc': 'Controls pie chart, bar chart, and badges.',

  /* Customize drawer — Categories tab */
  'drawer.cats.title': 'Your categories',
  'drawer.cats.add': 'Add category',
  'drawer.cats.namePlaceholder': 'Name (e.g. Health)',
  'drawer.cats.desc': 'Use short symbols (◇ ★ ♥ ● ▲ ◐) for the icon.',

  /* Customize drawer — Prefs tab */
  'drawer.prefs.languageDesc': 'Menus and settings are translated. Some longer passages stay in English for now.',
  'drawer.prefs.alertsDesc': 'Optional — also show a desktop notification when a budget threshold is crossed.',
  'drawer.prefs.lockDesc': 'Require a PIN when the app opens or returns from the background.',
  'drawer.prefs.lockNoPin': 'No PIN set yet — tap the toggle again to create one.',
  'drawer.prefs.lockChangePin': 'Change PIN',
  'drawer.prefs.lockSetPin': 'Set PIN',
  'drawer.prefs.lockAddDevice': 'Add device unlock',
  'drawer.prefs.syncSignedIn': 'Signed in',
  'drawer.prefs.syncError': 'Sync error — will retry automatically',
  'drawer.prefs.syncAccountId': 'Account ID {id}…',
  'drawer.prefs.syncLastSynced': 'Last synced {time}',
  'drawer.prefs.syncSignOut': 'Sign out',
  'drawer.prefs.syncSignIn': 'Sign in with Google',
  'drawer.prefs.syncDescIn': 'Your budget, balance, expenses, transfers, categories, theme and preferences sync automatically. The newest copy wins — edits from any device appear here.',
  'drawer.prefs.syncDescOut': 'Sign in to back up and sync your budget across devices with your Google account. Your data stays private — only you can read your copy.',
  'drawer.prefs.syncFbBefore': 'Sync is ready but needs a Firebase project. Open this file, find the ',
  'drawer.prefs.syncFbAfter': ' block, and paste your Firebase web app config. Then enable Google sign-in, authorize this site\'s domain (Authentication → Settings → Authorized domains), and create a Firestore database (rules are documented in the file). The app must be served over http(s), not opened as a plain file.',
  'drawer.prefs.shortcutPalette': 'Command palette',
  'drawer.prefs.shortcutAddSpend': 'Add new spend',
  'drawer.prefs.shortcutCustomize': 'Open customization',
  'drawer.prefs.shortcutCancelEdit': 'Cancel edit',
  'drawer.prefs.resetTheme': 'Reset theme to default',

  /* Money drawer */
  'drawer.money.title': 'Money',
  'drawer.money.topUpTitle': 'Top up budget',
  'drawer.money.toBudget': 'To budget',
  'drawer.money.toBalance': 'To balance',
  'drawer.money.addBalance': 'Add balance',
  'drawer.money.withdrawBalance': 'Withdraw balance',
  'drawer.money.balance': 'Balance',
  'drawer.money.after': 'After',
  'drawer.money.amountAdd': 'Amount to add',
  'drawer.money.amountToBudget': 'Amount to move to budget',
  'drawer.money.amountToReturn': 'Amount to return to balance',
  'drawer.money.amountWithdraw': 'Amount to withdraw',
  'drawer.money.note': 'Note (optional)',
  'drawer.money.notePlaceholderAdd': 'e.g. bonus, birthday money',
  'drawer.money.notePlaceholderReturn': 'e.g. took out the extra food money',
  'drawer.money.notePlaceholderBudget': 'e.g. extra cash for food',
  'drawer.money.descTopUp': 'Added to your total monthly budget — your daily allowance rises for the rest of the period.',
  'drawer.money.descToBudget': 'Moved out of your balance into this month\'s budget — your daily allowance rises for the rest of the period.',
  'drawer.money.descReturn': 'Moves money from your budget back to your balance — you can only take back what you moved in.',
  'drawer.money.descWithdraw': 'Removes money from your balance, e.g. to spend it elsewhere — it stays gone even if you stay under budget.',
  'drawer.money.descAddBalance': 'Money you add from outside the app — it raises your balance and is protected from spending.',
  'drawer.money.recent': 'Recent {kind}',
  'drawer.money.transfers': 'transfers',
  'drawer.money.topUps': 'top-ups',
  'drawer.money.actionAddFunds': 'Add funds',
  'drawer.money.actionToBudget': 'Move to budget',
  'drawer.money.actionReturn': 'Return to balance',
  'drawer.money.actionWithdraw': 'Withdraw',
  'drawer.money.actionAddBalance': 'Add to balance',

  /* Command palette */
  'palette.search': 'Search commands…',
  'palette.noMatch': 'No commands match.',
  'palette.navigate': 'Navigate',
  'palette.select': 'Select',
  'palette.close': 'Close',
  'palette.addExpense': 'Add new expense',
  'palette.openTheme': 'Open theme & customization',
  'palette.manageCategories': 'Manage categories',
  'palette.editBudget': 'Edit budget settings',
  'palette.moveMoney': 'Move money to budget',
  'palette.topUp': 'Top up budget',
  'palette.switchToLight': 'Switch to light mode',
  'palette.switchToDark': 'Switch to dark mode',
  'palette.downloadBackup': 'Download backup (JSON)',
  'palette.exportCsv': 'Export as CSV',
  'palette.restoreBackup': 'Restore from backup',
  'palette.comfortableDensity': 'Comfortable density',
  'palette.clearAll': 'Clear all data',

  /* Confirm dialog */
  'confirm.cancel': 'Cancel',
  'confirm.confirm': 'Confirm',
  'confirm.deleteEverything': 'Delete everything?',
  'confirm.deleteEverythingMsg': 'This removes all logged expenses, budget settings, and preferences. Download a backup first if you want to keep your data.',
  'confirm.breakPiggy': 'Break "{name}"?',
  'confirm.breakPiggyMsg': 'All {amount} moves back to your balance.',
  'confirm.deletePiggy': 'Delete "{name}"?',
  'confirm.deletePiggySaved': 'All {amount} saved in this piggy bank will move back to your balance.',
  'confirm.deletePiggySure': 'Are you sure you want to delete "{name}"?',

  /* Lock screen */
  'lock.pinTooShort': 'PIN must be at least 4 digits.',
  'lock.pinMismatch': "PINs don't match.",
  'lock.enterPin': 'Enter your PIN.',
  'lock.incorrectPin': 'Incorrect PIN.',
  'lock.biometricUnavailable': 'Device unlock unavailable — use your PIN.',
  'lock.setupTitle': 'Set an app lock PIN',
  'lock.lockedTitle': 'Ledger is locked',
  'lock.setupDesc': 'Choose a 4+ digit PIN. It is stored as a salted hash on this device only — never in your synced data.',
  'lock.unlockDesc': 'Enter your PIN to continue. Your data is not deleted — just hidden.',
  'lock.newPin': 'New PIN',
  'lock.pin': 'PIN',
  'lock.confirmPin': 'Confirm PIN',
  'lock.enable': 'Enable app lock',
  'lock.unlock': 'Unlock',
  'lock.useDevice': 'Use device unlock',
  'lock.forgot': 'Forgot PIN?',
  'lock.cancel': 'Cancel',

  /* Setup card & budget drawer */
  'setup.budgetSettings': 'Budget settings',
  'setup.bankBalance': 'Bank balance',
  'setup.bankBalanceDesc': 'Your bank balance. Transfers to the budget come out of this; leftover allowance is banked back into it.',
  'setup.overspendFromBalance': 'Overspends come from balance',
  'setup.overspendDesc': "When you spend more than a day's allowance, take it out of your bank balance. Off = covered by the monthly budget.",
  'setup.overspendToggle': 'Toggle overspend source',
  'setup.realign': 'Realign to 1st of this month',
  'setup.saveChanges': 'Save changes',
  'setup.subBalances1': 'Set a bank balance, track your daily allowance,',
  'setup.subBalances2': "and bank whatever you don't spend each day.",
  'setup.subBudget1': 'Set your budget, track your daily allowance,',
  'setup.subBudget2': "and carry over what you don't spend.",
  'setup.budgetAmount': 'Budget amount',
  'setup.startingBankBalance': 'Starting bank balance',
  'setup.startingBankBalanceDesc': 'The money you have right now — you can move it into your budget whenever you need it.',
  'setup.startTracking': 'Start tracking',
  'setup.or': 'or',
  'setup.restore': 'Restore from a backup',
  'setup.restoreDesc': 'Already have a ledger-backup .json file? Load it to pick up right where you left off.',

  /* Toasts */
  'toast.storageLimit': "Storage limit reached — this change works now but won't be saved after reload. Try a smaller file.",
  'toast.keptDeviceData': "Kept this device's data — synced up.",
  'toast.syncedFromCloud': 'Synced from cloud.',
  'toast.syncNotConfigured': "Sync isn't configured yet — see the Sync section in settings.",
  'toast.firebaseLoadFailed': "Couldn't load Firebase — check your internet connection and reload.",
  'toast.signedIn': 'Signed in — syncing is on. Change something to push your data.',
  'toast.signInCancelled': 'Sign-in cancelled.',
  'toast.popupBlocked': 'Popup blocked — allow popups for this page and try again.',
  'toast.domainUnauthorized': "This domain isn't authorized — add it in Firebase console → Authentication → Settings → Authorized domains.",
  'toast.needsHosting': 'Google sign-in needs http(s) hosting — serve this file from a local server or a host.',
  'toast.signInFailed': 'Sign-in failed.',
  'toast.signedOut': 'Signed out. Changes stay on this device.',
  'toast.signOutFailed': 'Sign out failed.',
  'toast.noNotificationSupport': "This browser doesn't support notifications.",
  'toast.notificationsEnabled': 'System notifications enabled.',
  'toast.notificationsNotEnabled': 'Notifications were not enabled.',
  'toast.notificationFailed': "Couldn't request notification permission.",
  'toast.unlocked': 'Unlocked.',
  'toast.appLockEnabled': 'App lock enabled.',
  'toast.deviceUnlockEnabled': 'Device unlock enabled.',
  'toast.deviceUnlockSetupFailed': "Couldn't set up device unlock on this device.",
  'toast.deviceUnlockUnavailable': 'Device unlock unavailable — use your PIN.',
  'toast.appLockRemoved': 'App lock removed. Your data is untouched.',
  'toast.invalidBudget': 'Enter a valid amount and period.',
  'toast.invalidBalance': 'Enter a valid balance.',
  'toast.budgetUpdated': 'Budget updated.',
  'toast.budgetSaved': 'Budget saved. Start tracking!',
  'toast.alertOver': '{label} is over budget ({pct}%).',
  'toast.alertAt': '{label} is at {pct}% of budget.',
  'toast.categoryBudgetLabel': '{label} budget',
  'toast.alertTitle': 'Ledger budget alert',
  'toast.invalidAmount': 'Enter a valid amount.',
  'toast.invalidTopUp': 'Enter a valid top-up amount.',
  'toast.notEnoughBalanceMove': 'Not enough balance — move at most {amount}.',
  'toast.movedToBudget': "Moved {amount} from your balance to this month's budget.",
  'toast.toppedUp': 'Topped up {amount} — added to your monthly budget.',
  'toast.addedToBalance': 'Added {amount} to your balance.',
  'toast.nothingToReturn': "Nothing to return — you haven't moved money to the budget. Please move some first.",
  'toast.returnTooMuch': "Can't return more than the {amount} you moved to the budget.",
  'toast.returned': 'Returned {amount} from your budget to your balance.',
  'toast.nothingToWithdraw': 'Nothing to withdraw — your balance is empty. Move money into it first.',
  'toast.notEnoughBalanceWithdraw': 'Not enough balance — withdraw at most {amount}.',
  'toast.withdrew': 'Withdrew {amount} from your balance.',
  'toast.transferRemoved': 'Transfer removed.',
  'toast.undo': 'Undo',
  'toast.actionUndo': 'Undo',
  'toast.restored': 'Restored.',
  'toast.piggyCreated': 'Created "{name}".',
  'toast.piggyRenamed': 'Piggy bank renamed.',
  'toast.goalSet': 'Savings goal set to {amount}.',
  'toast.goalCleared': 'Savings goal cleared.',
  'toast.notEnoughBalanceAdd': 'Not enough balance — add at most {amount}.',
  'toast.addedToPiggy': 'Added {amount} to {name}.',
  'toast.goalComplete': 'Goal complete for "{name}" — confetti! 🎉',
  'toast.piggyEmpty': '{name} is empty.',
  'toast.brokePiggy': 'Broke {name} — {amount} back to your balance.',
  'toast.cannotDeleteOnlyPiggy': 'Cannot delete the only piggy bank.',
  'toast.piggyDeleted': 'Deleted "{name}".',
  'toast.automatedEntries': 'Automated entries added.',
  'toast.pickStartDate': 'Pick a start date.',
  'toast.automationAdded': 'Automation added.',
  'toast.automationRemoved': 'Automation removed.',
  'toast.tripEnded': 'Trip ended.',
  'toast.chooseImage': 'Please choose an image.',
  'toast.imageTooLarge10': 'Image too large — pick one under 10MB.',
  'toast.receiptAttached': 'Receipt attached.',
  'toast.unreadableImage': "Couldn't read that image.",
  'toast.loggedTravel': 'Logged {foreign} ≈ {amount} in {category}.',
  'toast.logged': 'Logged {amount} in {category}.',
  'toast.spendUpdated': 'Spend updated.',
  'toast.spendRemoved': 'Spend removed.',
  'toast.duplicated': 'Duplicated {amount}.',
  'toast.backupDownloaded': 'Backup downloaded.',
  'toast.nothingToExport': 'Nothing to export.',
  'toast.csvExported': 'CSV exported.',
  'toast.invalidBackup': 'Not a valid ledger backup.',
  'toast.invalidBackupSettings': 'This backup has invalid budget settings.',
  'toast.invalidBackupTransfers': 'This backup has invalid transfers.',
  'toast.invalidBackupAutomations': 'This backup has invalid automations.',
  'toast.invalidBackupCategories': 'This backup has invalid categories.',
  'toast.invalidBackupCatBudgets': 'This backup has invalid category budgets.',
  'toast.invalidBackupPiggies': 'This backup has invalid piggy banks.',
  'toast.invalidBackupBalance': 'This backup has an invalid balance.',
  'toast.invalidBackupPiggy': 'This backup has an invalid piggy bank.',
  'toast.restoredEntries': 'Restored {count} entries.',
  'toast.unreadableFile': "Couldn't read that file.",
  'toast.chooseMedia': 'Please choose an image or video file.',
  'toast.mediaTooLarge': '{kind} too large — pick one under {size}MB.',
  'toast.wallpaperSet': '{kind} wallpaper set.',
  'toast.unreadableMedia': "Couldn't read that {kind}.",
  'toast.wallpaperRemoved': 'Wallpaper removed.',
  'toast.kindVideo': 'Video',
  'toast.kindImage': 'Image',
  'toast.kindVideoLower': 'video',
  'toast.kindImageLower': 'image',
  'toast.chooseImageFile': 'Please choose an image file.',
  'toast.imageTooLarge8': 'Image too large — pick one under 8MB.',
  'toast.cardPanelSet': 'Card panel set.',
  'toast.cardPanelRemoved': 'Card panel removed.',
  'toast.enterCategoryName': 'Enter a category name.',
  'toast.invalidCategoryName': 'Invalid or duplicate name.',
  'toast.categoryAdded': 'Category "{name}" added.',
  'toast.categoryInUse': "Can't delete — expenses use this category.",
  'toast.categoryRemoved': 'Category removed.',
  'toast.themeApplied': '{name} theme applied.',
  'toast.themeReset': 'Theme reset.',
  'toast.themeRestored': 'Restored previous theme.',
  'toast.paperTheme': 'Paper theme applied.',
  'toast.monoTheme': 'Mono theme applied.',
  'toast.allDataCleared': 'All data cleared.',
  'toast.enterFontName': 'Enter a Google Font name.',
  'toast.fontAlreadyAdded': '{name} is already added.',
  'toast.fontAdded': '{name} added from Google Fonts.',
  'toast.cardOrderReset': 'Card order reset.',
  'toast.catBudgetsSaved': 'Category budgets saved.',

  /* Computed labels — assembled outside the components (App.jsx) */
  'hero.labelBalance': 'Balance',
  'hero.labelAvailable': 'Available today',
  'card.auto.paused': 'Paused',
  'card.auto.dueToday': 'Due today',
  'card.auto.tomorrow': 'Tomorrow',
  'card.auto.inDays': 'in {n}d',
  'card.breakdown.rangeLabelPeriod': 'this budget period',
  'card.breakdown.rangeLabelWeek': 'the last 7 days',
  'card.breakdown.rangeLabelMonth': 'this calendar month',
  'card.breakdown.rangeLabelAll': 'all logged history',
  'card.breakdown.rangeLabelCustom': 'the selected range',

  /* Shared labels used by more than one surface. */
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.duplicate': 'Duplicate',
  'common.removeTransfer': 'Remove transfer',
  'common.receipt': 'Receipt',
  'palette.title': 'Command palette',
  'history.startDate': 'Start date',
  'history.maxDate': 'Max date',
  'chart.less': 'Less',
  'chart.more': 'More',
  'chart.spent': '{amount} spent',

  /* Notifications (Android). */
  'notif.channelName': 'Ledger Reminders',
  'notif.channelDesc': 'Daily spend reminders and budget alerts',
  'notif.dailyTitle': 'Ledger — Daily Log',
  'notif.dailyBody': 'Did you spend anything today? Tap to log your expenses.',
  'notif.dailyBodyLong': 'Did you spend anything today? Keep your budget and allowances accurate by logging your daily expenses.',
  'log.welcomeFirst': 'Welcome — log your first spend to start tracking.',
  'tab.travel': 'Travel',
  'travel.homeCurrency': 'Home currency',
  'travel.homeCurrencyDesc': 'Your own currency. Budgets, statistics and the hero are all reported in it.',
  'travel.rateAuto': 'Sync rate automatically',
  'travel.rateAutoDesc': 'Refresh the rate from the ECB reference rates when the trip starts or either currency changes.',
  'travel.refreshRate': 'Refresh rate now',
  'travel.rateFetching': 'Fetching the latest rate…',
  'travel.rateAsOf': 'Rate as of {date}',
  'travel.rateUpdated': 'Rate updated.',
  'travel.rateFailed': 'Could not reach the rate service. Keeping the saved rate.',
  'travel.rateNote': 'Home units per 1 {foreign}. Applied to new entries only — logged spends keep the amounts they were recorded with.',
  'travel.currenciesUsed': 'Currencies logged on this trip',
  'travel.currenciesUsedDesc': 'Switching the trip currency never rewrites entries you have already logged.',
  'travel.noCurrencies': 'Nothing logged on this trip yet.',
  'travel.currencies': '{n} currencies',
  'travel.homeCurrencyIs': 'Reported in {home}',
  'travel.ratePrivacy': 'Rate lookups send only the two currency codes to the ECB reference service.',
  'confirm.endTripTitle': 'End this trip?',
  'confirm.endTripMsg': 'Your travel spends stay in History, tagged with the trip — nothing is deleted. You can start a new trip any time.',
};
